python-semantic-release/python-semantic-release

tests/test_cli.py, tests/test_settings.py
Seems like this snuck in and tested for the wrong thing. The assertion function
is called assert_called_once_with(), only running assert_called_once() will
call the mock instead.
Refs #10.
=> Fixed name of assertion function.

semantic_release/cli.py, semantic_release/defaults.cfg, semantic_release/history/__init__.py, semantic_release/history/logs.py, semantic_release/vcs_helpers.py, tests/parsers/test_angular.py, tests/test_cli.py, tests/test_vcs_helpers.py
I changed the behaviours of finding current version and versioning
1. original way was using configed file to track version, I think using tag would be more straight forward. it returns 0.0.0 as default when it fails to find any version tag
2. instead of changing file content, I simply use tag to tract commits. I'm not sure this is a good way of versioning since I'm not a professional programmer.
=> add option to use tag instead of creating new commit when versioning

semantic_release/pypi.py, tests/test_pypi.py
Fixes current broken master. 
See discussion in: https://github.com/relekang/python-semantic-release/pull/69
=> fix: update call to upload to work with twine 1.9.1

semantic_release/vcs_helpers.py
Fix an error when the program was run in a non-git repository. It would not allow the help options to be run.
@relekang I know you wanted to put this `repo = Repo('.git', search_parent_directories=True)` line in it's own function. However that just adds unnecessary overhead and furthermore it does not lead to cleaner code.
=> Fix: error when not in git repository

CONTRIBUTING.rst
Change `.. _angular commit guidelins:` to `.. _angular commit guidelines:`
=> Typo, link broken

semantic_release/history/parser_angular.py, tests/parsers/test_angular.py
Per https://github.com/relekang/python-semantic-release/issues/101, this parser fails to match when the scope contains special characters such as: `.`, `,`, `*`, `&`, etc.
This fix opens up the contents of the scope to be more broad and supplies the corresponding tests.
(It also reuses the keys from `TYPES` to be a little cleaner and easier to maintain.)
=> fix(parser_angular): Fix non-match when special chars in scope

semantic_release/cli.py, semantic_release/vcs_helpers.py
This allows to run the program also from inner repository folders
The problem is in the call to `Repo` constructor which should get `'.'` for the current folder and not `'.git'`.
The current version of the code, from within other functions of this module, never checks `repo` was actually initialized. This lead to a number of other problems for which we'd probably like to show a nice error message too.
See for example this one:
```
:~/tmp$ semantic-release version --noop
Creating new version..
Traceback (most recent call last):
File "/home/luca/.local/bin/semantic-release", line 11, in <module>
load_entry_point('python-semantic-release', 'console_scripts', 'semantic-release')()
File "/home/luca/.local/lib/python3.4/site-packages/click/core.py", line 716, in __call__
return self.main(*args, …
```
=> fix: initialize git Repo from current folder

semantic_release/history/__init__.py, tests/test_history.py
Small change to the way the version is written to the config file it is read from.  This allows the formatting to be the same as before semantic-release changed it.
Prior behavior
`my_version_var="1.2.3"` => `my_version_var = '1.2.4'`
New behavior
`my_version_var="1.2.3"` => `my_version_var="1.2.4"`
I am using python-semantic-release with a Julia project and this change will allow for consistent formatting in my Project.toml file where the version is maintained
=> Maintain version variable formatting on bump

.gitignore
venv is ignored in config for flake8 and isort.
Should be ignored in git as well.
=> chore: ignore venv

semantic_release/vcs_helpers.py
Currently, running a semantic-release command from a subdirectory of the repo (e.g. in monorepos) will fail, during the commit phase, as it will try to add the file relative to the repository root. This makes it add the file relative to the cwd.
Might be related to https://github.com/relekang/python-semantic-release/issues/66
=> fix(vcs): allow cli to be run from subdirectory

readme.rst, semantic_release/__init__.py, semantic_release/history/__init__.py
Fixing [build not passing due to isort failure](https://circleci.com/gh/relekang/python-semantic-release/379).
Fixing circleci badge so it points to the master branch.
=> Fix isort and circleci badge

semantic_release/cli.py, tests/test_cli.py
This PR answers to an issue I had earlier https://github.com/relekang/python-semantic-release/issues/97
It keeps overriding the version variable in the code even if it's not commited. This allow the building process to find it and upload the correct version on PYPI. 
I just run the relevent test for this:
```
$ pytest tests/test_cli.py -k test_version_by_tag_should_call_correct_functions
tests/test_cli.py .                                                          [100%]
===================== 1 passed, 16 deselected in 0.49 seconds ======================
```
In addition I confirm the fix works in gitlab CI environment:
```
Current version: 0.2.1
Creating new version..
Current version: 0.2.1
Bumping with a minor version to 0.3.0.
...
Uploading distributions to …
```
=> Fixed setting version when using tag as source of the version string

semantic_release/vcs_helpers.py, tests/test_vcs_helpers.py
This is a necessary fix for gitlab integration.
For an illustration of the need and use for this fix, test was edited.
Fixes #139
Fixes #140
=> fix: manage subgroups in git remote url

docs/commit-log-parsing.rst, semantic_release/history/logs.py, semantic_release/history/parser_angular.py, tests/test_history.py
Also added perf to the types that trigger a patch update
Fixes #145
=> fix: update list of commit types to include build, ci and perf

docs/configuration.rst, requirements/base.txt, semantic_release/cli.py, semantic_release/settings.py, tests/__init__.py, tests/test_cli.py, tests/test_settings.py
This PR contains the load of configuration from two new sources :
* pyproject.toml (the new "standard" for python apps)
* command line using `-D`
Fixes #119 
Will be in conflict with #144 because of an added requirement (I will rebase on master when one is merged)
=> Add new config sources

docs/configuration.rst, docs/envvars.rst, requirements/base.txt, semantic_release/cli.py, semantic_release/hvcs.py, semantic_release/vcs_helpers.py, tests/mocks/mock_gitlab.py, tests/test_hvcs.py, tests/test_vcs_helpers.py
Adds python-gitlab as requirement.
Refactored github specific methods while keeping default behavior.
Also removed an unused return value for post_release_changelog.
Also refactored the secret filtering method.
Updated the related tests.
Fixes #121
Will be in conflict with #142 because of an added requirement (I will rebase on master when one is merged)
=> feat: make the vcs functionalities work with gitlab

docs/configuration.rst, semantic_release/cli.py, semantic_release/history/logs.py, tests/test_cli.py, tests/test_history.py
Before this commit, version was bumped in the file, but only committed
if version was obtained from `version_variable` (version_source == `commit`).
Also added a relevant test and a description for this new option.
Fixes #104
=> feat: allow users to get version from tag and write/commit bump to file

semantic_release/vcs_helpers.py, tests/test_vcs_helpers.py
Addresses https://github.com/relekang/python-semantic-release/issues/109#issuecomment-531053386
=> fix: support repo urls without git terminator

semantic_release/vcs_helpers.py, tests/test_vcs_helpers.py
Remove the dot from the second capture group to allow project names
containing dots to be matched.
Instead of a greedy '+' operator, use '*?' to allow the second group to
give back the '.git' (to avoid including it in the project name)
Fixes #151
=> fix: update regex to get repository owner and name for project with dots

semantic_release/vcs_helpers.py
The method getting all commits to consider for the release will now test
whether the version in input is a valid reference. If it is not, it will
consider the whole log for the repository.
evaluate_version_bump will still consider a message starting with the
version number as a breaking condition to stop analyzing.
Fixes #51
I could not find a simple way to test that.
=> fix: fallback to whole log if correct tag is not available

semantic_release/history/logs.py, semantic_release/history/parser_angular.py, semantic_release/history/parser_helpers.py, tests/parsers/test_angular.py, tests/test_history.py
This PR is mostly for #156 but I also added a change for point 16 of the specification : https://www.conventionalcommits.org/en/v1.0.0/
* Implement the use of exclamation points to describe breaking changes
* Allow the use of `BREAKING-CHANGE` as synonym of `BREAKING CHANGE`
I can put the second commit in another branch/PR if you prefer.
Fixes #156
=> Implement exclamation points for breaking changes

semantic_release/cli.py, semantic_release/history/__init__.py, setup.py
The get_current_version_by_config_file  and the replace_version_string methods now check for both variables defined as "variable= version" and "variable: version"
This allows for using a yaml file to store the version.
Closes #165
=> Allow for storing version in a variable using  ":" rather than "="

readme.rst
Fix the syntax of a broken bullet-point list in `README.rst`.
=> Fix broken list in README

semantic_release/hvcs.py, tests/test_hvcs.py
Use an `Authorization` header to authenticate to the GitHub API, as documented [here](https://developer.github.com/v3/#oauth2-token-sent-in-a-header), instead of deprecated query parameter authorization.
I've updated the test suite, however **I am yet to test these changes in a real run.**
Fixes #167.
=> Send access token in request header

semantic_release/history/logs.py, tests/test_history.py
Capitalize the first letter of commit messages in the changelog, regardless of whether they are capitalized in the commit itself. This helps to make the change notes look neater where some commits have capital letters and others do not, such as [this release](https://github.com/relekang/python-semantic-release/releases/tag/v4.5.1).
=> Capitalize changelog messages

semantic_release/hvcs.py
Update the MIME type used for uploading wheels to GitHub releases to `application/octet-stream`.
- `application/octet-stream` is more generic, but it is better than using a non-official MIME type.
- I noticed that the non-standard type was sometimes causing internal server errors on the GitHub API when trying to upload `.whl` files.
=> Use application/octet-stream for .whl asset uploads

semantic_release/vcs_helpers.py, tests/test_vcs_helpers.py
Format is:
"https://gitlab-ci-token:MySuperToken@gitlab.example.com/group/project.git"
Problem was due to the regex modification for #179
Fixes #181
=> fix: repair parsing of remotes in the gitlab ci format

AUTHORS.rst
Change AUTHORS.rst to have an automatically-updated grid of all users who have contributed to the repository, sorted by number of commits. The image also serves as a link to the [contributor graph](https://github.com/relekang/python-semantic-release/graphs/contributors).
Made with [contributors-img](https://contributors-img.web.app).
=> Make AUTHORS.rst dynamic

.github/workflows/main.yml
This was listed as one of the tasks on #109:
> Setup github actions for releasing this project by calling on the current source code.
I have set up a workflow to run on pushes to the `master` branch. For this to work, **the `PYPI_PASSWORD` secret must be set [here](https://github.com/relekang/python-semantic-release/settings/secrets/) by @relekang before merging.**
=> Set up releasing with GitHub Actions

.github/workflows/main.yml, Dockerfile, action.rst, action.sh, action.yml
Move [psr-action](https://github.com/AlphaMycelium/psr-action) into this repository. Fixes #196.
Documentation for the action is in `action.rst`. We may wish to add a link to this somewhere in the docs, and possibly move the file. I chose to place the action metadata directly into the root of the repository as `Dockerfile` needs to be there anyway as there is currently no other way to change the build context.
This also means that it is possible to publish the action on the GitHub Marketplace if we want to do so in the future, although this is not at all necessary for it to function (some changes to `readme.rst` would be required before publishing).
=> Move GitHub Action into this repository

semantic_release/history/logs.py, tests/test_history.py
Use of `capitalize()` capitalized the first letter of commit messages as expected, but all subsequent letters became lowercase. I have fixed this so that the other letters are not changed, and updated the testing to check for this.
This bug is quite evident in [the v4.11.0 release notes](https://github.com/relekang/python-semantic-release/releases/tag/v4.11.0) where the text 'GitHub Action' has no capital letters.
=> Fix capitalization in changelog

semantic_release/history/logs.py, semantic_release/history/parser_angular.py, semantic_release/history/parser_helpers.py, semantic_release/history/parser_tag.py
This improves readability as we can use attributes such as `bump` and `descriptions` instead of confusing numeric indices.
=> Use a named tuple for parsed commits

semantic_release/hvcs.py
This PR could be a good solution to the problem described in #210 .
In this PR I added a new parameter in the section code where a HTTP request is made to the [Github API for releases](https://developer.github.com/v3/repos/releases/#create-a-release) specifically the section where a release is created. I included the release name and set it to the tag version by default.
=> Version tag as default release name in Github

docs/commit-log-parsing.rst
I just bumped (no pun intended) into a `'tuple' object has no attribute 'bump'` error. 
This is due to a change in the last major release:
```
$ git diff v4.11.0 upstream/master -- semantic_release/history/parser_angular.py
-    return (
+    return ParsedCommit(
level_bump,
TYPES[parsed.group('type')],
parsed.group('scope'),
```
Now it accepts an instance of `ParsedCommit` instead of a nested `Tuple`. I updated the doc to reflect this.
=> doc: updated doc with new ParsedCommit object instead of nested Tuple

action.sh, action.yml, docs/automatic-releases/github-actions.rst, docs/automatic-releases/index.rst, docs/automatic-releases/travis.rst, docs/configuration.rst, docs/envvars.rst, semantic_release/cli.py, semantic_release/pypi.py, tests/test_pypi.py
- Allow setting the environment variable `PYPI_TOKEN`.
- Tokens are preferred over username and password if both are set.
Fixes #213
=> Support easier use of PyPI API tokens

.github/workflows/stale.yml
Any issues which are labelled as a question will be marked as `stale` after 4 days with no activity, and then closed after a further 3 days. This doesn't affect other types of issues.
=> Close stale questions automatically

semantic_release/history/logs.py, semantic_release/history/parser_angular.py, semantic_release/history/parser_helpers.py, semantic_release/history/parser_tag.py, tests/parsers/test_helpers.py, tests/test_history.py
Check each paragraph of the commit's description for breaking changes, instead of only a body and footer.
- Breaking changes will always be detected when squashing commits
- Multiple breaking changes can be found in one commit
Fixes #200
=> Check all paragraphs for breaking changes

docs/configuration.rst, semantic_release/cli.py, semantic_release/defaults.cfg, semantic_release/history/logs.py, tests/history/test_markdown_changelog.py, tests/test_cli.py
Display a link in the changelog to the page comparing commits between this release and the previous one.
This is configured using the config option `compare_link`, and is off by default since GitHub displays a "compare" menu next to the release for the same purpose:
Fixes #218
=> Add link to view commit range in changelog

semantic_release/cli.py, tests/test_cli.py
Adapt the CLI tests so that pytest can capture the log output, and display it if there is a failure. This helps with debugging.
=> Capture logging output in tests

docs/configuration.rst, semantic_release/changelog/__init__.py, semantic_release/changelog/changelog.py, tests/test_changelog.py
Add an alternative changelog component (`semantic_release.changelog.changelog_table`) which displays each section as a row in a table, like this:
| Type | Change |
| --- | --- |
| Feature | Commit 1 (sha)<br>Commit 2 (sha) |
| Fix | Commit 3 (sha) |
Fixes #237.
=> Add changelog_table component

docs/configuration.rst
I had a little trouble figuring out how to use a non-setup.py build command, so I thought it would be helpful to update the docs with an example of how to do this.
=> docs: give example of multiple build commands

semantic_release/cli.py
This appears to have changed in 15b1f650f29761e1ab2a91b767cbff79b2057a4c, since [`click-log` uses stderr by default](https://github.com/click-contrib/click-log/blob/0d72a212ae7a45ab890d6e88a690679f8b946937/click_log/core.py#L46-L55).
Fixes #250, this PR is an alternative to #252.
=> Send changelog to stdout

semantic_release/history/__init__.py, tests/history/test_version.py
Closes #258 
This enables `re.MULTILINE` matching for `version_pattern` specifiers by default.
It could be argued that this is actually not a fix but a breaking change, as technically using `^` or `$` would match the start/end of the entire file contents with the current version of code, but in practice I doubt this is likely to be the case.
=> Support multiline version_pattern matching by default

action.yml
According to [the documentation](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputsinput_idrequired), `inputs.<input_id>.required` is a required field, adding it as false to all inputs where it's missing.
=> Add `required` to all inputs in action metadata

.github/workflows/pr.yml
The contributing guide says that the project should itself follow the Angular commit convention, but there is nothing to enforce it AFAIK.
I had a similar problem on a project where I'm using `python-semantic-release` and I've added a Github action to test it on CI, you might find it useful too.
I also recently added [a pre-commit hook](https://github.com/alessandrojcm/commitlint-pre-commit-hook) to get even earlier feedback, let me know if you're interested.
=> Check commit logs with commitlint in CI

semantic_release/hvcs.py
Github has recently moved their documentation under https://docs.github.com/ including their REST API. This change update the links in docstrings accordingly.
=> Update links to Github docs

docs/configuration.rst, docs/index.rst
I noticed a couple of internal references in the documentation page are formatted properly and sections are not linked as expected.
=> docs: fix broken internal references

docs/configuration.rst, semantic_release/history/logs.py, semantic_release/settings.py, tests/history/test_changelog.py
When the scope is set, include it in changelogs, e.g.,
`"feat(x): some description"` becomes:
`* **x**: some description`
in the changelog. This is similar to how the Node semantic release (and conventional-changelog-generator) generate changelogs. If scope is not given, it's omitted.
Add a new config parameter changelog_scope to disable this behavior when set to `False`
=> feat(logs): include scope in changelogs

docs/configuration.rst, semantic_release/defaults.cfg, semantic_release/history/logs.py
Some cleanup from #281
- Move the default for changelog_scope from inline to defaults.cfg
- Add missing `.. _config-changelog_scope:` header in docs
=> refactor(history): move changelog_scope default

docs/configuration.rst, semantic_release/cli.py, semantic_release/defaults.cfg, semantic_release/history/logs.py, semantic_release/settings.py, tests/history/test_version_bump.py, tests/test_settings.py
The discussion is on #280 .
Set this option to `false`, it will avoid bump from 0.y.z to 1.0.0 automatically.  This is useful when develop in initial development stage.
=> New option: major_on_zero

semantic_release/changelog/changelog.py, tests/test_changelog.py
GitHub release notes automagically link to the PR, but changelog markdown doesn't. Replace (#123) at the end of a message with a markdown link.
=> feat(changelog): add PR links in markdown

semantic_release/changelog/changelog.py, tests/test_changelog.py
While, e.g., https://github.com/owner/repos/pull/123 will work, https://github.com/owner/repos/issues/123 should be safer / more consistent, and should avoid a failure if someone adds an issue link at the end of a PR that is merged via rebase merge or merge commit.
=> fix(changelog): use "issues" link vs "pull"

docs/configuration.rst, semantic_release/cli.py, semantic_release/pypi.py, tests/test_cli.py, tests/test_pypi.py
In my use case, the build_command generates some binary files with pyinstaller that should not be uploaded to PyPI (but should still be uploaded in Github Release page).
This change allow to specify some globs that should be sent to PyPI, instead of hardcoded `*`.
```
upload_to_pypi_glob_patterns = *.tar.gz,*.whl
```
=> feat: add `upload_to_pypi_glob_patterns` option

semantic_release/hvcs.py, tests/test_hvcs.py
If an error occurs while uploading files to github release, it's now logged as a warning and use raise_for_status feature from python request lib.
This fix issue when uploading files without extension to github. In this case, mimetype can't be guessed. Then, a POST request is performed without Content-Type header, but it fails with an error response from Github API.
=> Ensure GitHub content type is always defined (application/octet-stream)

semantic_release/changelog/changelog.py, semantic_release/cli.py, semantic_release/helpers.py, semantic_release/history/__init__.py, semantic_release/history/logs.py, semantic_release/history/parser_angular.py, semantic_release/history/parser_tag.py, semantic_release/hvcs.py, semantic_release/pypi.py, semantic_release/settings.py, semantic_release/vcs_helpers.py, tests/test_pypi.py
Some logger invocation were raising "TypeError: not all arguments converted during string formatting", because of invalid argument count given.
This also refactor some other logs to use f-strings.
=> fix(logs): Fix TypeError when enabling debug logs

semantic_release/cli.py
Skip removing dist files when `upload_pypi` or `upload_release` are not set.
This way, people don't have to explicitly set `remove_dist()` to `False` when `build_dist()` has not run.
I _think_ this should be the correct behavior, and this seemed like a relatively simple way to accomplish it.
Open to suggestions on a) other / better ways to accomplish this and b) best / simplest ways to add a unit test for this.
Alternately, I could move the `if upload_pypi` and `if upload_release` conditionals inside that outer block:
https://github.com/relekang/python-semantic-release/blob/1b386c6d78772fd09351697c83fd4e39dfae1821/semantic_release/cli.py#L265
and then publish the changelog, however, I'm not sure whether that would be the wrong order of operations
=> fix(cli): skip remove_dist where not needed

semantic_release/changelog/changelog.py, semantic_release/hvcs.py, tests/test_hvcs.py
While Gitlab already has an env var that should provide the vanity URL, this supports a generic 'hvcs_domain' parameter that makes the hostname configurable for both GHE and Gitlab.
This will also use the configured hostname (from either source) in the changelog links
Fixes: #277
=> feat(hvcs): add hvcs_domain config option

semantic_release/history/__init__.py, setup.py
This resolves deprecation warnings, and updates this to a more 3.x compatible syntax
=> fix(history): require semver >= 2.10

semantic_release/history/__init__.py, tests/history/test_version.py
The changes in #297 mistakenly omitted coercing the return value to a
string. This resulted in errors like:
`can only concatenate str (not "VersionInfo") to str`
Add test case asserting it's type `str`
=> fix(history): coerce version to string

docs/index.rst
Add some new sections to the Getting Started area of the documentation. Fixes #299.
=> Extend getting started page

docs/configuration.rst, semantic_release/cli.py, semantic_release/dist.py, tests/test_cli.py, tests/test_dist.py
It may sounds strange to have no `build_command` at all, but my build is performed for 3 distincts OS (linux, macos, windows) with pyinstaller inside a first github action job, and then another job grabs generated artifacts to publish using semver. There's no build command inside PSR to perform because artifacts to publish are already produced by github action.
=> feat(build): allow falsy values for build_command to disable build step

action.sh, docs/commands.rst, semantic_release/__main__.py, semantic_release/cli.py, semantic_release/history/logs.py, tests/test_cli.py
This new command can be integrated in the build process before the effective release, ie. to rename some files with the version number.
Users may invoke `VERSION=$(semantic-release print-version)` to retrieve the version that will be generated during the release before it really occurs.
=> feat(print-version): add print-version command to output version

docs/configuration.rst, docs/index.rst, semantic_release/history/__init__.py, semantic_release/settings.py, semantic_release/vcs_helpers.py, setup.py, tests/history/test_version.py, tests/test_settings.py
This introduce a new `version_toml` configuration property that behaves like `version_pattern` and `version_variable`.
For poetry support, user should now set `version_toml = pyproject.toml:tool.poetry.version`.
This introduce an ABC class, `VersionDeclaration`, that can be implemented to add other version declarations with ease.
`toml` dependency has been replaced by `tomlkit`, as this is used the library used by poetry to generate the `pyproject.toml` file, and is able to keep the ordering of data defined in the file.
Existing `VersionPattern` class has been renamed to `PatternVersionDeclaration` and now implements `VersionDeclaration`.
`load_version_patterns()` function has been renamed to `load_version_declarations()` and now return a list of `VersionDeclaration` implementations. …
=> feat: add toml files support for version declaration (#245, #275)

semantic_release/history/__init__.py
Add multi-line regex support to the version replace function.
This change addresses issue 306: https://github.com/relekang/python-semantic-release/issues/306 and is an extension of the earlier change done here https://github.com/relekang/python-semantic-release/pull/259/commits.x
=> fix: use multiline version_pattern match in replace

docs/configuration.rst
Looks like 2 parts `poetry` and `tool` were flipped in the example.
You can see a working example in [a repository from the author](https://github.com/inetum-orleans/docker-devbox-installer/blob/47d4d8f9779681e4cd5395f9af2b252151342a99/pyproject.toml#L27).
And [a failed attempt of mine](https://github.com/browniebroke/django-codemod/issues/318) by using the value from the docs, which caused [an error in Github actions](https://github.com/browniebroke/django-codemod/runs/1777220358?check_suite_focus=true#step:4:181).
=> docs: fix `version_toml` example for Poetry

README.rst, action.yml, docs/commit-log-parsing.rst, docs/index.rst, setup.py
Semantic Versioning is the name of the specification. Therefore it is a proper noun. This patch corrects the incorrect casing for Semantic Versioning.
=> docs: correcting casing on proper noun

semantic_release/ci_checks.py, tests/ci_checks/test_jenkins.py
Includes a ci check handler to verify jenkins.
Unlike other ci systems jenkins doesn't generally prefix things with
`JENKINS` or simply inject `JENKINS=true` Really the only thing that is
immediately identifiable is `JENKINS_URL`
=> feat(checks): Add support for jenkins ci

docs/configuration.rst, docs/envvars.rst, semantic_release/pypi.py, tests/test_pypi.py
Addresses #310
* Defaults to using `$HOME/.pypirc` file for credentials if `PYPI_TOKEN` or (`PYPI_USERNAME` and `PYPI_PASSWORD`) are not specified.
* Allows use of `--repository <repository>` for twine upload. This also comes from `$HOME/.pypirc`.
=> feat: allow the use of .pypirc for twine uploads

setup.py
Doesn't look like the proper fix, but [it solved the problem](https://github.com/browniebroke/netlify-builds/runs/2669817097?check_suite_focus=true#step:4:285) for me. 
Fixes #336
=> fix: pin tomlkit to 0.7.0

semantic_release/cli.py, semantic_release/defaults.cfg, semantic_release/settings.py, tests/test_cli.py
I'm trying to use `python-semantic-release` in a monorepo, where I need to version individual libraries separately. This sadly gets blocked `python-semantic-release`: Some libraries could have the same version and while versioning would like to create the same (an existing) tag.
This PR solves this problem (the easy way for now) by adding an option to omit the tagging of commits. This obviously only works with the `version_source="commit"` option.
I'm relatively new to python, so any feedback on the implementation is highly appreciated :)
OT: it would be nice if `python-semantic-release` would support custom version string formats, e.g. like [lerna](https://github.com/lerna/lerna/tree/main/commands/version) for js does - this would enable alpha, beta, canary releases as well as custom …
=> Feature: add option to omit tagging

.github/workflows/main.yml, docs/automatic-releases/github-actions.rst
This prevents race conditions if there are consecutive pushes.
=> Recommend setting a concurrency group for GitHub Actions

setup.py
The current version has a Deprecation warning:
`DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()`
=> chore(deps): bump responses to latest version

semantic_release/history/__init__.py, tests/history/test_version.py, tests/test_cli.py
This extracts some refactoring out of #346 which I think are beneficials:
- Refactor `VersionDeclaration` to use `pathlib`
- Add a test to reproduce the out-of-order issue with `tomlkit` 0.7.2 + dotty-dict
=> Refactor `VersionDeclaration` to use `pathlib`

semantic_release/hvcs.py, tests/mocks/mock_gitlab.py, tests/test_hvcs.py
Used the release api from python-gitlab instead of the outdated tag api.
Solves this [issue](https://github.com/relekang/python-semantic-release/issues/350)
=> fix: use release-api for gitlab

semantic_release/history/__init__.py, semantic_release/history/parser_scipy.py, tests/parsers/conftest.py, tests/parsers/test_scipy.py
Closes: #368 
Adds a simple scipy style parser + unit tests
The tests generate a matrix of commit messages (from parts that I faithfully borrowed from my repos and scipy), and they parse correctly.
When I naively run the parser on my target repo (`semantic release -v debug changelog` in project root), however, the changelog remains empty. I can confirm that it indeed selects the scipy_parser added here, and I know that at least some of the commits should be parsed correctly (they are generated by the tests). Does python-semantic-release need an initial tagged commit to get going? If not, any other idea where I am being stupid?
**Edit:** The version appears to be detected correctly:
```bash
$ semantic-release -v debug --noop version
debug: Main args: {'force_level': None, 'post': False, …
```
=> feat(parser): add scipy style parser

semantic_release/vcs_helpers.py
Should improve/fix #365
Now all following tags will be treated as tags with versions and result in `1.2.3` version:
- `v1.2.3`
- `1.2.3`
- `1.2.3-alpha`
=> feat: Add support for non-prefixed tags

docs/configuration.rst, semantic_release/defaults.cfg, semantic_release/vcs_helpers.py, tests/test_vcs_helpers.py
Related to #316
Ability to define custom git tag format via `tag_format` config option
Also the JS implementation of the semantic release [already has the same feature](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#tagformat)
=> feat: custom git tag format support

semantic_release/changelog/compare.py, semantic_release/history/__init__.py, semantic_release/history/logs.py, semantic_release/hvcs.py, semantic_release/vcs_helpers.py
Otherwise, hvcs release could not be created (+another side effects?) if `tag_format` config option has a non-default value
=> fix: hardcoded v-prefix in the git tags

tests/test_repository.py
When run on windows the following tests fail due to a different separator:
```
> tox
...
FAILED tests/test_repository.py::RepositoryTests::test_repo_with_custom_dist_globs - AssertionError: Lists differ: ['dist\\*.tar.gz', 'dist\\*.whl'] != ['dist/*.tar.gz', 'dist/*.whl']
FAILED tests/test_repository.py::RepositoryTests::test_repo_with_custom_dist_path - AssertionError: Lists differ: ['custom-dist\\*'] != ['custom-dist/*']
FAILED tests/test_repository.py::RepositoryTests::test_repo_with_custom_pypi_globs - AssertionError: Lists differ: ['dist\\*.tar.gz', 'dist\\*.whl'] != ['dist/*.tar.gz', 'dist/*.whl']
```
This PR should take care of that by using os.path.join() when defining expected values
=> test: Prevent test_repo_with_custom_* from failing when run on window due to different path seperator

semantic_release/hvcs.py, tests/test_hvcs.py
- Turns out that response from `https://gitea.com/api/swagger#/repository/repoCreateStatus` is sometimes a list 
- Also fixes gitea asset upload
=> fix(gitea): build status and asset upload

semantic_release/hvcs.py, tests/test_hvcs.py
- seems that [this](https://github.com/relekang/python-semantic-release/pull/420)  did not fix the asset uploading
- I have tested this locally so this "should" fix it
=> fix(gitea): use form-data for asset upload

Dockerfile
This PR adds `git-lfs` to the GitHub Actions docker container. Not really sure how I can test this, other than to say I have it working with a `git-lfs` enabled repository using my fork.
Fixes #409
=> feat: add git-lfs to docker container

setup.py
- tests for a tomlkit regression don't fail anymore with newer tomlkit
- keep comment in setup.py about tomlkit being pinned at some point in time
refs #336
=> chore(dependencies): unpin tomlkit dependency

semantic_release/cli.py, tests/test_cli.py
The `get_current_version` function accepts a `prerelease` argument which was never passed.
=> fix(prerelase): pass prerelease option to get_current_version

docs/configuration.rst, semantic_release/cli.py, tests/test_cli.py
> I would like to use semantic-release to publish new version tags in git, without updating any files/creating additional commits.
https://github.com/relekang/python-semantic-release/issues/354
Perhaps this was the original intention of this functionality - but I may be biased because this is the functionality I am after. Alternatively, this functionality could exist under a different config setting as per OP's issue: `tag_only` or something like that.
=> issue 354: if version_source=tag,then  don't read/write to a config file

semantic_release/history/__init__.py, tests/history/test_version.py
Related to https://github.com/relekang/python-semantic-release/issues/354
Version `7.28.0` introduced new `version_source=tag_only` functionality. However, `publish`, `version` and `print_version` rely on [get_current_version function](https://github.com/relekang/python-semantic-release/blob/7bffd66a84111efc31f1e4379466b5edcb461133/semantic_release/history/__init__.py#L223), which doesn't implement the new functionality.
```bash
$ pip show python-semantic-release 
Name: python-semantic-release
Version: 7.28.0
Summary: Automatic Semantic Versioning for Python projects
Home-page: http://github.com/relekang/python-semantic-release
Author: Rolf Erik Lekang
Author-email: me@rolflekang.com
License: MIT
Location: /Users/raf/virtualenvs/index-service/lib/python3.9/site-packages
Requires: click, …
```
=> fix: version_source=tag_only current version should ignore config file

.github/workflows/pr.yml, semantic_release/cli.py, semantic_release/history/__init__.py, semantic_release/vcs_helpers.py, setup.cfg, tests/history/test_version.py, tests/test_cli.py, tests/test_vcs_helpers.py
Related to https://github.com/relekang/python-semantic-release/issues/434
When digging into the issue I encountered some more misalignments in my previous provided code for the prerelease feature.
With this PR I want to fix this issues and also do some normalisation work in the package.
@danth @williamluke4 @relekang 
~~Curiously, locally all tests pass. I checked and the test fail because of methods which traverse the git log... 
Locally all commits starting from the current branch are analysed (ending with the init commit) - but in the ci pipeline, there is only one commit (Some merge commit I can't find nowhere else... ). Any Idea why this is happening and how to prevent it?~~
Solved: The problem was, that by default githubs `actions/checkout@v2` checks out a single merge commit. It …
=> Fix/Refactor: Prerelease 

.gitignore, semantic_release/hvcs.py, setup.py
.. would fail with
```
semantic_release/hvcs.py:581: error: Argument "files" to "post" of "Session" has incompatible type "List[Tuple[str, Tuple[str, BufferedReader, str]]]"; expected "Optional[Union[Mapping[str, Union[SupportsRead[Union[str, bytes]], str, bytes]], Mapping[str, Tuple[Optional[str], Union[SupportsRead[Union[str, bytes]], str, bytes]]], Mapping[str, Tuple[Optional[str], Union[SupportsRead[Union[str, bytes]], str, bytes], str]], Mapping[str, Tuple[Optional[str], Union[SupportsRead[Union[str, bytes]], str, bytes], str, MutableMapping[str, str]]]]]"
Found 1 error in 1 file (checked 22 source files)
ERROR: InvocationError for command /Users/briancho/src/oss/python-semantic-release/.tox/mypy/bin/mypy --ignore-missing-imports semantic_release (exited with code 1) …
```
=> chore: fix test and doc failures

docs/configuration.rst, semantic_release/defaults.cfg, semantic_release/settings.py, semantic_release/vcs_helpers.py, tests/test_vcs_helpers.py
In GH Actions I want to use a ssh Deploy Key to push changes to a _protected_ branch because not every user's GITHUB_TOKEN is allowed to push to _protected_ branches but Deploy Keys are.
If I specify a `GH_TOKEN` such as `GITHUB_TOKEN` in a GitHub Action with enough permission to publish a GitHub Release, python-semantic-releases will also use that user's token to push version and tag changes to the repository.
The user running the action though might not have enough permission to push to a _protected_ branch even if grating some degree of permission to its `GITHUB_TOKEN`. Only Deploy Keys or Admin user's `GITHUB_TOKEN`(or Personal Access Tokens) can.
Add an option that will allow to use the token to submit GitHub Releases while will avoid using that token for pushing changes to the …
=> Allow using ssh-key to push version while using token to publish to hvcs

.github/workflows/main.yml, semantic_release/cli.py, semantic_release/history/__init__.py, tests/history/test_version.py, tests/test_vcs_helpers.py
The tests were failing due to the addition of methods and tests that get the current release by tag without pulling all of the tags.  Adding a `fetch-depth` of `0` corrected the issue.
=> fix ci tests

semantic_release/history/__init__.py, tests/history/test_version.py
Version in init file: 0.0.24-beta.0
Detected current release version: 0.0.24
Detected current version: 0.0.2
Generated new version: 0.0.3
Tested the current regex pattern in isolation against the above version and see that match[1] is stripping the 4 in the patch version
Logs:
debug: Parsing current version: path=PosixPath('src/analytics_calc/init.py') pattern='version *[:=] *["\'](https://github.com/relekang/python-semantic-release/pull/%5Cd+%5C.%5Cd+%5C.%5Cd+(-beta%5C.%5Cd+)?)["\']' num_matches=1
debug: Regex matched version: 0.0.24
debug: get_current_version_by_config_file -> 0.0.24
debug: get_current_release_version_by_commits()
debug: Checking commit 19569b7cf15c3d21c7ed45dc335a386aed4d997e
debug: Checking commit 32ae4df6ee88c31e145f5109aa89c782c1c4795c
debug: Checking commit …
=> fix: Wrong current release version captured when patch has more than one digit

semantic_release/hvcs.py, tests/test_hvcs.py
Allows custom github servers to have assets uploaded and compatible with github.com as well.,
Note: `hvcs_api_domain` is really `hvcs_api_root` for github enterprise servers, as the API root would typically be `https://my_custo_github.com/api/v3`.
Closes: #456
=> fix: Ensure that assets can be uploaded successfully on custom github servers

semantic_release/history/__init__.py
This suddenly failed on my in a CI build today, I see that exceptions bubble up to the CLI and are printed to the output so adding a message to the error should make it user-visible.
=> refactor: Added text for empty ValueError

semantic_release/history/__init__.py, semantic_release/vcs_helpers.py, tests/history/test_version.py, tests/test_vcs_helpers.py
Delay construction of version and release patterns until runtime.
This will allow to use non-default prerelease tag.
=> fix: prerelease tag in version patterns

semantic_release/history/__init__.py, semantic_release/vcs_helpers.py, tests/history/test_version.py, tests/test_vcs_helpers.py
Builds upon https://github.com/relekang/python-semantic-release/pull/472 from @browniebroke and adds the commit_subject functionality
Fixes: https://github.com/relekang/python-semantic-release/issues/442
=> fix: ignore dependencies versions bump when parsing version from commit logs

action.sh, docs/automatic-releases/github-actions.rst, docs/commands.rst
Add `ADDITIONAL_OPTIONS` as an additional command for the github action.
Using it with `--noop` on PRs as shown below allows to verify that new configurations or versions will run successfully on the main branch:
```yaml
name: Semantic Release
on:
push:
branches:
- master
pull_request:
branches:
- master
jobs:
noop-release:
if: github.ref != 'refs/heads/master'
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
with:
fetch-depth: 0
- name: Python Semantic Release Test
uses: relekang/python-semantic-release@master
with:
github_token: ${{ secrets.GITHUB_TOKEN }}
repository_username: __token__
repository_password: ${{ secrets.PYPI_TOKEN }}
additional_options: --noop
release:
if: github.ref == 'refs/heads/master'
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
with: …
```
=> feat: add ADDITIONAL_OPTIONS for gh action

action.sh
I added double quotes to fulfill https://www.shellcheck.net/wiki/SC2086 but this doesn't work for the default (empty env var).
=> fix: allow empty additional options

semantic_release/history/__init__.py
When `commit_subject` is configured but no commits are made by this lib or `version_source=tag_only` is used the changes in https://github.com/relekang/python-semantic-release/pull/476 introduced an error.
Now the `commit_subject` is only used to find the version pattern in commit messages and not in files or tags.
=> fix: don't use commit_subject for tag pattern matching

action.yml
Fixes the warning displayed at the start of an action run:
=> fix: Declare additional_options as action inputs

semantic_release/history/__init__.py
I _think_ this is a bug, but let me know if not...
`get_current_release_version()` doesn't work when using `tag_only` version source... it defaults back to `get_current_release_version_by_commits` which may show nothing
=> fix: :bug: fix get_current_release_version for tag_only version_source

semantic_release/history/__init__.py
Strings in `semantic_version.history` are causing `DeprecationWarning: invalid escape sequence` warnings. This PR corrects these warnings by using raw strings. 
```
semantic_release/history/__init__.py:29
semantic-release/semantic_release/history/__init__.py:29: DeprecationWarning: invalid escape sequence \.
return f"-{config.get('prerelease_tag')}\.\d+"
-- Docs: https://docs.pytest.org/en/latest/warnings.html
```
=> fix: corrections for deprecation warnings

semantic_release/history/logs.py, semantic_release/vcs_helpers.py
resolves #171 
i tested this locally.
the whole-testsuite seems to still pass.
i have no clue how to test this with the given test-infrastructure tho.
suggestions and contributions to cover this with tests are highly welcome
=> fix: Fix changelog generation in tag-mode (#171)

docs/envvars.rst, semantic_release/repository.py, tests/test_repository.py
Adds support for TWINE_CERT, as proposed [here](https://github.com/python-semantic-release/python-semantic-release/issues/521).
=> feat(repository): fixes #521, adding support for TWINE_CERT

Dockerfile, action.sh, action.yml, docs/action.rst, docs/configuration.rst
Add ability to add an SSH key for verifying commits as mentioned here: https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#ssh-commit-signature-verification
Updated documentation accordingly.
Install `stable-bpo` version of `git` ([1:2.34.1-1~bpo11+1](https://packages.debian.org/source/stable-backports/git)) in docker image as the stable version ([1:2.30.2-1](https://packages.debian.org/source/stable/git)) doesn't support signing commits with SSH. 
Added documentation for the action now that there are more than a few options.
=> feat: add signing options to action

semantic_release/history/logs.py
Running `semantic-release changelog` currently fails to identify "the last commit in [a] release" because the compared commit messages have superfluous whitespace. (Likely related to the issue causing https://github.com/relekang/python-semantic-release/issues/490)
The logic to iterate through the commits, to identify the boundary between the two versions, fails to identify the release commit message generated by semantic-release, and skips all the commits.
This ultimately results in no commits being printed as part of the changelog.
I have a log looking like this:
```
$ git log --oneline
a501da0 (HEAD -> main, tag: 0.2.0-dev.4, origin/main) 0.2.0-dev.4
812e796 Merge pull request #41 from [...]
8ccc600 (origin/todo) refactor: [...]
e06c3b4 Merge pull request #40 from [...]
94a4d35 …
```
=> fix: changelog release commit search logic

.github/workflows/main.yml, .github/workflows/pr.yml, setup.py
GHA workflows are failing without this due to https://github.com/actions/setup-python/issues/544\#issuecomment-1332535877
=> ci: remove python3.6 from GHA, add python3.10 and python3.11

semantic_release/cli.py
Reported version by `publish` and `print-version` does not match
I expected to have both to return the same next version for a same set of arguments.
While using:
```
python-semantic-release 7.32.2
Python 3.9.12
```
And for this given git history containing patches only:
```
* 40187c5 (HEAD -> develop) patch: change 2 (mrjk, 45 seconds ago)
* 969375d patch: change 1 (mrjk, 45 seconds ago)
* 6f01669 patch: change 0 (mrjk, 45 seconds ago)
* 17fcb7d (tag: v0.1.3-beta.2, origin/develop) bump: version v0.1.3-beta.2 (semantic-release, 83 seconds ago)
```
If I try to get the next version, I have:
```
$ semantic-release print-version --noop --prerelease
0.1.3-beta.3
```
Which is fine,  but if I publish next version, I have:
```
$ semantic-release publish --noop --prerelease
Current version: …
```
=> fix: inconsistent versioning between print-version and publish

docs/troubleshooting.rst
- change contraction to a possessive pronoun
=> docs: grammar in `docs/troubleshooting.rst`

docs/automatic-releases/github-actions.rst
In order to avoid 'Repository not found: relekang/python-semantic-release.' error in github actions
=> fix(docs): Update repository name in github actions

semantic_release/helpers.py, semantic_release/history/parser_emoji.py, tests/test_helpers.py
Emojis (`patch_emoji`, `minor_emoji` and `major_emoji`) are given as comma-separated values. Since they are not trimmed, one can easily get into headaches. This PR adds striping to the config values.
=> Trim emojis from config

semantic_release/defaults.cfg
According to the "official" [node module](https://github.com/carloscuesta/gitmoji/blob/master/packages/gitmojis/src/gitmojis.json) the Gitmojis have changed. This PR updates the default emojis for patch and minor versions.
In addition, it allows the usage of utf-8 symbols. So one can either use `:sparkles` or `✨` in their commit messages.
=> Update Gitmojis according to official node module and make utf-8 symbols available

semantic_release/cli.py, semantic_release/hvcs.py, tests/test_cli.py, tests/test_hvcs.py
Since @wintero92 will not be able to complete his PR #547 in the next couple of months, I have corrected the tests so that we can already see this version in release.
=> fix: if prerelease, publish prerelease (python-semantic-release#544) (continuing #547)

README.rst
The "Test Status" badge was updated to address a recent breaking change in the GitHub actions API. All the badges updated to add links to the appropriate resources for end-user convenience.
=> fix(readme): update broken badge and add links

docs/automatic-releases/github-actions.rst, docs/configuration.rst, semantic_release/defaults.cfg, semantic_release/settings.py, semantic_release/vcs_helpers.py
When running the application from a sub-directory in the VCS, the option use_only_cwd_commits will filter out commits that does not changes the current working directory, similar to running commands like `git log -- .` in a sub-directory.
Relevant, but not complete solution, for #168.
=> feat: add option to only parse commits for current working directory

semantic_release/changelog/__init__.py, semantic_release/changelog/changelog.py, tests/test_changelog.py
Adding an extra new line after each header and between sections fixes the following 2 `markdownlint` ([VS Code](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint), [GitHub](https://github.com/DavidAnson/markdownlint)) errors for changelogs generated by this package:  
* [`MD022` - Headings should be surrounded by blank lines](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md022---headings-should-be-surrounded-by-blank-lines)
* [`MD032` - Lists should be surrounded by blank lines](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md032---lists-should-be-surrounded-by-blank-lines)
=> fix: generate markdown linter compliant changelog headers & lists

semantic_release/vcs_helpers.py
Since version `7.34.0`, empty commits are ignored when scanning commits for commit messages that should trigger releases.
```bash
git init
git commit -m "fix: initial commit" --allow-empty
echo "[semantic_release]" >> setup.cfg
echo "version_source = tag_only" >> setup.cfg
semantic-release version --verbosity=DEBUG
```
Output with `python-semantic-release==7.33.5` (as expected):
```
Creating new version
debug: get_current_version_by_tag()
debug: get_last_version(, pattern='(\d+\.\d+\.\d+(-beta\.\d+)?)')
debug: no version found, returning default of v0.0.0
debug: get_current_version_by_tag -> 0.0.0
debug: get_current_release_version_by_tag()
debug: get_last_version(, pattern='v?(\d+\.\d+\.\d+(?!.*-beta\.\d+))')
debug: no version found, returning default of v0.0.0
debug: …
```
=> fix: consider empty commits

semantic_release/cli/commands/changelog.py, semantic_release/version/algorithm.py, semantic_release/version/translator.py, tests/unit/semantic_release/version/test_algorithm.py
=> fix: invalid version in Git history should not cause a release failure

docs/migrating_from_v7.rst
=> docs: clarify v8 breaking changes in GitHub action inputs

docs/migrating_from_v7.rst
=> docs: correct version_toml example in migrating_from_v7.rst

docs/configuration.rst, pyproject.toml, semantic_release/cli/commands/main.py, semantic_release/cli/config.py, semantic_release/cli/util.py, tests/command_line/test_main.py, tests/unit/semantic_release/cli/test_util.py
With this change, PSR will no longer error if it cannot find appropriate configuration in the default
pyproject.toml file, or in the file specified by -c/ --config when that option is given. Instead it will use the default configuration values
=> fix: handle missing configuration

pyproject.toml
Hi there, my first PR to the project.
The tests in GitHub Actions run on Python 3.11 as well. I guess you should add it to the project metadata then.
=> docs: add Python 3.11 to classifiers in metadata

semantic_release/data/templates/CHANGELOG.md.j2, semantic_release/version/version.py, tests/fixtures/git_repo.py, tests/unit/semantic_release/changelog/TEST_CHANGELOG.md.j2, tests/unit/semantic_release/changelog/test_default_changelog.py
when release notes are generated, tag version is set instead of baser version. Before breaking change we were having base version format "v{version}" that reflects the actual published version. I think tag formatting is used for avoiding multi packages conflicts in the same repo.
=> fix(changelog): use base version without tag format by default

docs/configuration.rst
This was the reason why my versions would not get updated in `version.py` - I followed _the docs_, and _the docs_ had a typo ;)
=> docs: Fix typo missing 's' in version_variable[s] in configuration.rst

pyproject.toml
Hi there,
I think if python-semantic-release officially supports Python >= 3.7, you can get rid of the explicit `dataclasses` dependency (python_version < '3.7.0').  Is that right?
Feel free to close, if you still want to support older versions.
=> chore(deps): remove obsolete dataclasses dependency

semantic_release/helpers.py
Hi
In trying to get a custom commit parser working, I noticed this.
Thanks
=> fix: dynamic_import() import path split

Dockerfile, action.yml, docs/algorithm.rst, docs/commands.rst, docs/commit-parsing.rst, docs/configuration.rst, docs/index.rst, docs/migrating_from_v7.rst, docs/multibranch_releases.rst, docs/strict_mode.rst, semantic_release/hvcs/_base.py, semantic_release/hvcs/gitlab.py, tests/const.py, tests/unit/semantic_release/changelog/TEST_CHANGELOG.md.j2
Hi, I think these might all be typos, right?
I was unsure in this line:
https://github.com/python-semantic-release/python-semantic-release/blob/3abfb7ac216b9ad439de24fda60eca84038e850e/tests/unit/semantic_release/version/test_declaration.py#L83
Is this a typo or some sort of fuzzy matching?
`r"(?P<vrsion>.*)"`
=> docs: fix typos

.github/workflows/main.yml, .github/workflows/pr.yml, pyproject.toml
Python 3.12 (without -dev) is scheduled for release on 2023-10-02: https://peps.python.org/pep-0693/
That is in approximately two weeks.
This PR proposes the following changes:
- add Python version 3.12-dev to the CI test runs
- add Python 3.12 to project.classifiers
The tests are passing. So I guess your library is ready for Python 3.12. :)
=> chore: add ci test job for python 3.12-dev

pyproject.toml
I'm trying to use python-semantic-release in Airflow. With version 2.6.3 of airflow, version 5.12.0 of importlib-resources is forced.
I'd like to bump this dependency since it presents no impact on the project.
Thanks
=> build(deps-dev): bump importlib-resources from 5.7 to 5.12.0

pyproject.toml
This PR proposed the following changes:
- add changelog url
- add issues url
- use lowercase for project urls
Your current homepage url points to the documentation. I added a documentation url, but left the hompeage url as well. Should I remove one of those?
These new urls will render with a nice icon on PyPI.
Refs: https://daniel.feldroy.com/posts/2023-08-pypi-project-urls-cheatsheet
=> docs: update project urls

semantic_release/cli/commands/version.py
On Windows systems, if the shell you get is cmd instead of executing the command it opens a shell
This is because instead of telling it cmd /c COMMAND it is sent cmd -c COMMAND
=> fix: Error when running build command on windows systems

.github/workflows/main.yml, .github/workflows/pr.yml, pyproject.toml
Python 3.12 was released on 2023-10-02 and is now available for GitHub actions runners as well.
This PR proposes the following changes:
- replace Python version 3.12-dev with 3.12 to the CI test runs
- add Python 3.12 to tox envlist
The tests are still passing. So I guess your library is now really ready for Python 3.12.
=> chore: add tests for python 3.12

CHANGELOG.md, docs/changelog_templates.rst, docs/index.rst, pyproject.toml, semantic_release/changelog/template.py, semantic_release/cli/commands/changelog.py, semantic_release/cli/commands/version.py, semantic_release/cli/common.py, semantic_release/cli/config.py, semantic_release/hvcs/_base.py, semantic_release/hvcs/util.py, tests/command_line/conftest.py, tests/command_line/test_changelog.py, tests/command_line/test_version.py, tests/const.py, tests/fixtures/example_project.py, tests/fixtures/git_repo.py, tests/util.py
Allow end users to override the default `Jinja2` template for rendering release notes. 
If a file named `.release_notes.md.j2` exists in the configured [`template_dir`](https://python-semantic-release.readthedocs.io/en/latest/configuration.html#config-changelog-template-dir), it is used to render the release notes of a given VCS release.
Implements #660 
1. c3f54c837072106e1bc470a32e2027e12fbf9ff6
2. 476cedb135e7397e88eec6b25cb07c151ffb6559
3. d648d79d40dba66d213bfd071a595d69d0bd8504
4. 3565dcd178255be500ec161e3e042aae557b84f7
- 8dc1283ab19d2a148add449f28828d8ef69dd78c and 884bbf849988bc46883a5ceccb862dd2ed1dc521 update the [changelog_templates.html](https://python-semantic-release.readthedocs.io/en/latest/changelog_templates.html) Sphinx page to describe how to use this feature
- …
=> feat: Allow user customization of release notes template

docs/migrating_from_v7.rst
Update the migration documentation for clarity of what `publish` command does now as opposed to before.
This section was a great write up to explain how I can go about migrating from `v7` to `v8`, however I was very confused about the order of operations when I reviewed the version and publish code.  I corrected the steps and alignment to each command in this PR after reviewing the code segments.  This adjustment lines up with how `version` can/will run a new build and the second statement about removing the wrapped `twine` functionality.
=> docs(migration): fix comments about publish command

tests/command_line/test_main.py
Fix issues when running command line tests when the global git configuration includes `commit.gpgsign = true`.
As my environment has the global configuration setting `commit.gpgsign` set to `true`, the scenario tests inherit this default setting.  When the scenario tests execute a commit, this setting applies. It was properly disabled in scenario tests but was not disabled in the fixture used by this `main` command line test.  This change replicates the scenario `git_repo.py` fixtures config modifications.
=> test(commandline-main): prevent git gpgsign config from failing tests

semantic_release/cli/commands/version.py, tests/command_line/test_version.py, tests/const.py, tests/fixtures/example_project.py
Fix a TypeError when one of the modified files during `version` command adds a file that matches a `.gitignore` pattern.
I personally don't commit a change to the version number in my files when building my distribution. To enable my software to know its version number I write it to a file that is imported `_version.py`. This file is generated by the build system `setuptools_scm` and it makes it easy to have this file git-ignored.  When semantic-release executed the update to the version file, it tried to add it to the index and git rejects with an exit code unless the `--force` command is provided.  My recommendation (this implementation) is to catch this error gracefully and print a warning to the developer in case they did not desire it to be ignored.
I modified the current testing …
=> fix(cmd-version): handle committing of git-ignored file gracefully

semantic_release/cli/config.py, tests/command_line/test_main.py
Gracefully handle a TypeError when repository is in a detached HEAD state as occurs naturally in GitLab CI/CD environments.
As I was setting up this library to run within GitLab CI/CD, I ran into an unhandled TypeError because of the detached HEAD state that GitLab's Runner Helper image sets up the environment by default.  This is problematic due to the branch detection mechanism used in `python-semantic-release`. I opted to have the code gracefully catch this error and display a rationale to the user.  
I have devised a way to manually resolve this problem in GitLab in the step before `semantic-release` is called but have not implemented an internal correction method (match the detached HEAD SHA to an equivalent branch and checkout). At the current time it will be up to the developer to …
=> fix(config): gracefully fail when repo is in a detached HEAD state

docs/configuration.rst
Update mis-spelled words and adjust wording for clarity
I adjusted the environment variable section a bit because if people don't read and just look for code blocks then we have an example in there that is not recommended and its not easy to tell its not recommended.  I recommend we just eliminate that example completely but state it clearly that it should not be done that way.
Other items were just clarity of language. Feel free to pass feedback if my wording is not clear either.
=> docs(configuration): adjust wording and improve clarity

semantic_release/cli/commands/main.py, tests/command_line/test_main.py, tests/fixtures/example_project.py
Improve handling of exceptions to provide a useful message to user without stack trace
If a user puts in an invalid configuration setting, the configuration validator will throw a ValidationException that we do not catch gracefully. This causes python to dump a stack trace and hide the pretty ValidationError that pydantic provides by default.  
In order to set up the test appropriately, I found it useful to add a fixture that will modify the configuration file accordingly.  Meanwhile, I noticed that the implementation of example project was a bit fragile as exceptions are not handled well with generators or context managers unless explicitly using try/finally. With this modification I was able to align it more with the setup/teardown generator style fixtures as pytest recommends.
Created …
=> fix(cli): gracefully output configuration validation errors

docs/commit-parsing.rst
The code sample was wrong - correct elsewhere in the file
=> docs: minor correction to commit-parsing documentation

semantic_release/helpers.py, tests/unit/semantic_release/test_helpers.py
Expand the compatibility to as many variants of valid git remote urls as git allows
In preparation to facilitate the request of #734, first we need to properly parse all valid git urls.  I found a stackoverflow reference that listed many of the possible urls and I built a unit test to match a set of them.  During implementation, I opted to coerce each input into an URL-parse compatible format which then could be easily broken up into the valid parts.
Build a paramaterized unit test with all the expected valid tests.
```sh
git fetch origin pull/771/head:pr-771
git checkout pr-771~1 --detach
pytest tests/unit/semantic_release/test_helpers.py
git merge --ff-only pr-771
pytest tests/unit/semantic_release/test_helpers.py
```
=> feat(utils): expand parsable valid git remote url formats

semantic_release/cli/config.py, semantic_release/hvcs/__init__.py, semantic_release/hvcs/_base.py, semantic_release/hvcs/gitea.py, semantic_release/hvcs/github.py, semantic_release/hvcs/gitlab.py, tests/unit/semantic_release/cli/test_config.py
Update the configuration parser to optionally default to the VCS specific token
In preparation to facilitate the request of #734, I need to find a way to solve the missing token when the `remote.type` is `none`.  This led me to determining that it would be helpful if we looked for the default token names for each of the VCS. This refactor enables the configuration to be aware of each VCS's default.  
Current downside is that `Gitea` does not provide a pre-authed CI-like token based on [this discussion](https://github.com/go-gitea/gitea/issues/20394).  I just guessed to use `GITEA_TOKEN`. I could potentially have it be empty instead, which would force the user to provide it.
Consideration also should be made for `GitLab` as GitLab's default token `CI_JOB_TOKEN` has permissions problems …
=> refactor(config): enable default environment token per hvcs

semantic_release/cli/commands/generate_config.py, tests/command_line/test_generate_config.py, tests/unit/semantic_release/cli/test_config.py
Ensure that when converting pydantic configuration objects into TOML, the TOML comes out parsable.
When working on #782, I ran into a problem where the TOML generated was unparsable due to the use of a subclass of IntEnum.  The `LevelBump(IntEnum)` caused the string produced by the `__str__()` to not be surrounded in quotations in the resulting TOML. 
This led to discovering that the Tomlkit developer refuses to attempt to address serialization of enums due to the shifting position of Python implementation of enums across versions of python (sdispater/tomlkit#237).  Since Tomlkit will not support enums, we must prevent enum objects from being passed to `tomlkit.dumps()`.  Pydantic saves the day with the parameter `mode` for the `model_dumps()` function which can be set to `json` and it …
=> fix(cli-generate-config): ensure configuration types are always toml parsable

docs/configuration.rst, docs/index.rst
Improve readability of defaults relating to `remote.token`.
I forgot to update the docs with #774, and I was thinking this would be clearer than the paragraph of consecutive if-then statements in text.
```sh
sphinx-autobuild --open-browser docs docs/_build/html
```
http://127.0.0.1:8000/configuration.html#token-dict-env-str
=> docs(configuration): change defaults definition of token default to table

CONTRIBUTING.rst
Add additional testing and development instructions for an contributing developer
I was unfamiliar with the some of tools and the configuration of this project. This adjustment helps other developers not have to figure it out but instead have the commands on hand to know what to do.
I manually executed all the new instructions added here during my development. I ran a VSCode debugger on a pytest function and was able to break at a desired breakpoint in the test and in the code.  For the docs, the `_build` was important for the `sphinx-autobuild` watchdog server to not trigger a rebuild on the creation of the docs initially.
=> docs(contributing): add docs-build, testing conf, & build instructions

docs/configuration.rst, semantic_release/cli/config.py, semantic_release/commit_parser/_base.py, tests/unit/semantic_release/cli/test_config.py, tests/util.py
In preparation for a simpler configuration with dependent default options and a per parser-type config generator, this PR pulls the defaults from the associated commit parser value if not provided.
Simplifying the amount of options that the user must specify especially for non-angular parsers. The defaults for non-angular parsers are only available in the documentation. This way they just have to remove the options value completely after a `generate-config` command and they can just use the built-in defaults.  I have plans to extend the `generate-config` functionality in the future to allow these defaults to be generated instead and this PR would need to be accepted first.
Added additional unit tests which validated that the default commit parser options were loaded for the proper commit …
=> fix(config): set commit parser opt defaults based on parser choice

docs/configuration.rst
This note is specific to the `commit_author` configuration property, but exists both in its correct place and as a note under the higher-level heading `Settings`
=> docs: Remove duplicate note in configuration.rst

.github/dependabot.yaml
This PR proposes the following changes:
- add a grouped github-actions section to the dependabot config
This will generate a single pull request containing all updates to GitHub Actions in the project.
What do you think?
Refs:
- https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/
Example PR:
- https://github.com/afuetterer/python-semantic-release/pull/10
=> ci: add grouped github-actions section to dependabot config

tests/command_line/conftest.py, tests/command_line/test_changelog.py, tests/command_line/test_version.py, tests/conftest.py, tests/fixtures/example_project.py, tests/fixtures/git_repo.py, tests/scenario/test_template_render.py, tests/unit/semantic_release/cli/test_config.py, tests/unit/semantic_release/hvcs/test_gitea.py, tests/unit/semantic_release/hvcs/test_github.py, tests/unit/semantic_release/version/test_declaration.py
Improve speed of test code and reduce the number of IO operations
In other development towards changelog testing, I came across the high use of IO operations as we rebuild a project with each test case.  This causes a lot of IO operations, and even more so on the use of git.  I followed the rabbit hole, and this PR is the first of a few that help increase the test execution speed through deliberate abstraction/modularity.  I felt it all at once would be way to confusing and too much for a good review.
Besides checking the result here in the CI, I originally was able to confirm the caching mechanism through the VSCode debugger and many break points through the code to see how many times each fixture was called.  Once this commit was implemented, the session scope ensured that it was only …
=> test(fixtures): cache the base example project directory

semantic_release/commit_parser/util.py, tests/unit/semantic_release/commit_parser/test_util.py
Due to windows line-endings `\r\n`, it would improperly split the commit description (it failed to split at all) and cause detection of Breaking changes to fail. The breaking changes regular expression looks to the start of the line for the proper syntax.
Resolves: #820
=> fix(util): properly parse windows line-endings in commit messages

pyproject.toml
This PR proposes the following changes:
- update the ruff configuration to use e.g. `[tool.ruff.lint]` and `[tool.ruff.lint.flake8-quotes]`
Refs:
- https://docs.astral.sh/ruff/configuration/
=> chore: modernize ruff configuration to work with ruff >= 0.2

semantic_release/version/algorithm.py, tests/unit/semantic_release/version/test_algorithm.py
Improve performance and fix flaw in BFS algorithm
I was testing a complex Git Flow repository and found that if the breadth first search reached a previously visited node even if it didn't find the version it was looking for it would abort with None.  This was incorrect as the version it was looking for was deeper on the tree.  This appears when you a have a branch that has more than 1 commit on it and has merged back into a base branch. The other branch also must have more commits on it than the branch prior to the version it is looking for.  The graph looks like this:
```
* merge commit 6 (start)
|\
| * commit 5
| * commit 4
|/
* commit 3
* commit 2
* commit 1
* v1.0.0
```
During a breadth first search looking for `v1.0.0`, a textbook BFS algorithm will visit the nodes in the following …
=> fix(algorithm): correct bfs to not abort on previously visited node

docs/configuration.rst, docs/index.rst, semantic_release/cli/config.py, semantic_release/hvcs/__init__.py, semantic_release/hvcs/_base.py, semantic_release/hvcs/bitbucket.py, tests/unit/semantic_release/changelog/test_changelog_context.py, tests/unit/semantic_release/hvcs/test_bitbucket.py
This pull request adds support for the Bitbucket remote vcs. Bitbucket doesn't support releases like Github but I added a skeleton class anyway so that users can use `semantic-release version` without having to use the `--no-vcs-release` flag. It still pushes a tag to the remote vcs which creates archives so it's nice to be able to use semantic-release without necessarily having actual releases in the remote vcs.
=> feat: add bitbucket

semantic_release/helpers.py, tests/unit/semantic_release/test_helpers.py
This pull request fixes an issue when the URL contains a dash.
Expected normal parsing:
```
https://gitlab.company-net.com/username/myproject.git
```
Actually is `ValueError`.
=> Bad url with dash

docs/commands.rst, pyproject.toml, semantic_release/cli/commands/version.py, tests/command_line/test_version.py
This adds a the command `semantic-release current-version` so semantic-release can be used to determine the current tag on the branch based on semantic-release config.
=> feat(version): Add new version print flags to display the last released version and tag.

MANIFEST.in
Create a more comprehensive `sdist` (which is expected to include your testing and documentation) without causing changes to the wheel artifact
I used the documentation on the setuptools website for MANIFEST syntax and read through the error logs of the build step.  Ends up the `recursive-include` syntax was incorrect so I fixed that. Also it is unnecessary to lay out specific files as build will automatically include certain files which we defined explicitly (`pyproject.toml`, `LICENSE`, `MANIFEST.in`, etc.).  Lastly, I added the tests and docs to the MANIFEST and was happy to see that they only were included with the sdist but then ignored in the wheel packaging.
I ran the build locally and then unpacked the `sdist` & `whl` files separately and evaluated the contents using the …
=> build(MANIFEST): fix sdist contents to include docs & tests

.github/dependabot.yaml
Quiet down the number of dependabot PRs for every minor or patch version that comes out when the current range definition will automatically pull the latest dependency for the user/developer.
This more so comes from experience that the default strategy for dependabot does not bode well for using ranges. It has a tendency to bump the lowest part of the range up until there is no more range!  That was definitely not the intention so this strategy adheres to ranges and only opens a PR when a version outside of the range is available.
=> chore(dependabot): adjust conf to relax bumping flexible requirement specs

.github/stale.yml
Enable the GitHub Stalebot application to manage long term issues and PRs that never get closed or remembered because of lack of time/interest 
This is an awesome capability built into GitHub that helps reduce the clutter and reminds both external members and contributors to keep track of issues and PRs created.  If unresponsive then it will be closed after a period of time. It has a two stage approach where it marks issues/prs as stale with a warning and then actually closes it at a later designated time.  I put in fairly gracious timelines more than what I normally use for projects.  We have a number of PRs that seem prior to v8 and plenty of tickets that never were closed before. This will help keep it manageable. 
- Will need a maintainer to create the label `confirmed`. Of course, I …
=> chore(stalebot): add config to manage aging issues & PRs

docs/commit-parsing.rst, semantic_release/changelog/release_history.py, semantic_release/changelog/template.py, semantic_release/cli/config.py, tests/util.py
In lieu of the `v9` release where support for `3.7` was removed, this PR cleans up any additional code adjustments specific to `3.7` support.
=> refactor: drop other 3.7 references

semantic_release/helpers.py, tests/unit/semantic_release/test_helpers.py
Currently, the implicit ssh url regex only allows letters and numbers. These urls can include special characters from email addresses (._-). This corrects that regex and adds an applicable unit test condition.
=> Allow special characters in implicit ssh urls

semantic_release/cli/commands/changelog.py, semantic_release/cli/commands/cli_context.py, semantic_release/cli/commands/generate_config.py, semantic_release/cli/commands/main.py, semantic_release/cli/commands/publish.py, semantic_release/cli/commands/version.py, semantic_release/cli/config.py, tests/command_line/conftest.py, tests/command_line/test_help.py, tests/unit/semantic_release/cli/test_config.py, tests/util.py
- Ensure help information is always accessible even when configuration is invalid
This resolves #840, by means of lazy loading of the configuration file until the runtime context is actually needed. Which ever subcommand actually needs the runtime context object will access the property of the click context object which is set in the top level click function.  The reason this was not working already is because when a subcommand help is accessed it fully runs through the `main()` click function first before evaluating the subcommand's options.  This was causing the failure too soon.  I found some click documentation for the `@click.pass_obj` which helps manage our type confusion in this passing of a newly defined CliContextObj which handles the lazy loading.
I wrote a few unit tests for …
=> fix(cli-help): enable subcommand help even if config is invalid 

semantic_release/cli/commands/version.py, tests/command_line/test_version.py, tests/util.py
Adjust order of operations during `semantic-release version` command to build changelog prior to `build_command` execution. 
I desire to have the ability to generate the changelog and mark versions without creating a commit or tag, and also the ability to bundle the changelog into the bundle. This is currently unavailable due to the order of execution.  This modification moves changelog generation up before the build command which allows the build_command to bundle it in.  The commits don't change either but instead this consolidates adding to the index into one git command prior to the commit.
Successful refactor is captured by:
- `tests/command_line/test_version.py::test_version_only_update_files_no_git_actions()` - where the CHANGELOG is now a part of the commit of changed files along …
=> feat(cmd-version): changelog available to bundle

semantic_release/cli/commands/version.py
Restricts the git push command to only push the explicit tag we created which will eliminate the possibility of pushing another tag that could cause an error.
Resolve: #803
=> fix(cli-version): change implementation to only push the tag we create

semantic_release/hvcs/gitea.py, tests/unit/semantic_release/hvcs/test_gitea.py
Hello again
For a gitea repo how about implying the `api_domain` (when not specified) from `domain`? Saves a bit more config.
Thanks
PS how about inferring `domain` itself (when not provided) from pyproject.toml `project.urls.repository` (if provided)? I had a quick look but given the code drops everything but `[tool.semantic_release]` from pyproject.toml immediately after parsing it, the change seemed like more than a one-liner. Happy to have a look if you think it's sensible.
=> feat: infer gitea api_domain from domain, if unspecified.

semantic_release/cli/github_actions_output.py, tests/unit/semantic_release/cli/test_github_actions_output.py
Resolve #884 bug of a missing trailing newline which is expected by GitHub Actions
The bug existed because `str.join()` only inserts a value between elements which means the last element did not receive a newline. 
Refactored the existing tests to more visually define the exact output value that should be placed in the output file. The tests now properly detect when the newline is missing.
```sh
git fetch origin pull/885/head:pr-885
git checkout pr-885~1 --detach
pytest tests/unit/semantic_release/cli/test_github_actions_output.py
git merge --ff-only pr-885
pytest tests/unit/semantic_release/cli/test_github_actions_output.py
pytest
```
=> fix(gh-actions-output): fixed trailing newline to match GITHUB_OUTPUT format

semantic_release/hvcs/bitbucket.py, semantic_release/hvcs/gitea.py, semantic_release/hvcs/github.py, semantic_release/hvcs/gitlab.py, tests/unit/semantic_release/hvcs/test_bitbucket.py, tests/unit/semantic_release/hvcs/test_gitea.py, tests/unit/semantic_release/hvcs/test_github.py, tests/unit/semantic_release/hvcs/test_gitlab.py
Hi
Whilst fixing the tests for #675 I noticed something with `hvcs_api_domain` and `api_url`.
`hvcs_api_domain` only has `https://` stripped if read from the environment. As a result `api_url` can end up as `https://https://...` if `hvcs_api_domain` is explicitly passed with the url scheme (which the tests do). I'm not sure if it's intentional given the test case,  but it's surely not for `api_url` 😀
Maybe this is better as an issue rather than PR, but in case it really is trivial here's a mod normalising `hvcs_api_domain` across github/gitea/gitlab by always stripping `https://` (and `hvcs_domain`, too).
Thanks
=> Always strip url scheme from domain

semantic_release/hvcs/github.py, tests/command_line/test_changelog.py, tests/unit/semantic_release/hvcs/test_github.py
Extend support to handle GitHub Enterprise Server for on-premise usage with a non sub-domain api url
Resolve #895
=> feat: extend support to on-prem GitHub Enterprise Server

docs/changelog_templates.rst, semantic_release/changelog/context.py, semantic_release/cli/commands/changelog.py, semantic_release/cli/commands/publish.py, semantic_release/cli/commands/version.py, semantic_release/cli/config.py, semantic_release/errors.py, semantic_release/hvcs/__init__.py, semantic_release/hvcs/_base.py, semantic_release/hvcs/bitbucket.py, semantic_release/hvcs/gitea.py, semantic_release/hvcs/github.py, semantic_release/hvcs/gitlab.py, semantic_release/hvcs/remote_hvcs_base.py, tests/unit/semantic_release/changelog/test_changelog_context.py, tests/unit/semantic_release/changelog/test_default_changelog.py, tests/unit/semantic_release/cli/test_util.py, tests/unit/semantic_release/hvcs/test__base.py, tests/unit/semantic_release/hvcs/test_bitbucket.py, tests/unit/semantic_release/hvcs/test_gitea.py, tests/unit/semantic_release/hvcs/test_github.py
Refactor changelog context to gather filters from the features available in the HVCS 
Resolve: #671
This allows for more specialization long term regardless of functions that are not common across all VCS's. This also includes a refactoring of the base classes to divide up functionality that is can deviate when certain functions are unavailable for a specific HVCS. 
Created tests that evaluate each filter function of a carefully crafted changelog template that purposefully exercises each HVCS's changelog filters.
=> feat: changelog filters are specialized per vcs type

docs/commands.rst, docs/multibranch_releases.rst, semantic_release/cli/commands/version.py, tests/command_line/test_version.py
Prior to this change, --prerelease performed the role that --as-prerelease now does, which was an unintentional breaking change to the CLI compared to v7.
--prerelease now forces the next version to increment the prerelease revision, which makes it consistent with --patch, --minor and --major, while --as-prerelease allows for the usual next version to be converted to a prerelease befoer it is applied to the project
Resolves: #639
=> feat(cli): correct --prerelease use and add --as-prerelease

.github/workflows/main.yml, .github/workflows/pr.yml, pyproject.toml
- Improve defaults of local testing
- resolve deprecation warning from ruff
For local use, the coverage plugin messes up debuggers and slows down the test execution.  This change keeps the coverage metrics around as an enforcement mechanism in the CI but does not force the developer to constantly adjust the test configuration for debugging purposes.  Luckily `xdist` will handle debugging just fine but will be in subprocesses which is a change that is more manageable and obvious rather than the coverage (just doesn't hit a breakpoint ever). 
Also resolved the ruff option deprecation of the `--show-source` option which has been changed to `--output-format=full`.
=> chore: update ruff cmd & ci execution

.github/workflows/stale.yml
Add some bot logic to further help manage issues and PRs for the maintainers
Initially we have generic stale updates that help identify long forgotten issues/PRs, which works but since I provided the flag to confirm an issue this possibly puts an issue/PR in a state that could still fall through the cracks and never find a resolution.  Therefore I added a job that stalebot will specifically target the `confirmed` tag and make sure it reminds the maintainers to provide an update on the status to the submitter every 2 months
Secondly, when someone submits an issue and the maintainer responds, certain submitters either miss it or never respond to the additional request for information.  To indicate the issue is waiting for reply, I use the `awaiting-reply` tag to indicate this. The new …
=> chore(stalebot): add unresponsive & issue reminder jobs with stalebot

action.sh, action.yml
- Update the GitHub action definitions to include the `--tag` command line option added in `v8.4.0`
- Resolve: #906
First I must add the definition to the `action.yml` file to ensure that users can provide a `tag` directive to their `GitHub Action` definition.  This then translates to a new environment variable that is passed to the `action.sh`.  That variable must be read in order to determine if it should add a true or false command line option to the `semantic-release version` command.  Lastly, I decided to remove all the extra default values from the `action.*` files because they we are maintaining multiple locations where the defaults are set for the project.
=> fix(gha): add missing `tag` option to GitHub Action definition

Dockerfile, docs/configuration.rst, semantic_release/cli/commands/version.py, tests/command_line/test_version.py
Enable more sophisticated build command scripts by passing valuable environment variables to subprocess
In order to give users more context to the environment in which the `build_command` is executed, this PR defines a set of environment variables to pass to the subprocess.  One such action is to pass the newly determined next version value into the environment in case it needs to be used for the build process.  This is helpful for configuring tools like `setuptools_scm` which need the `SETUPTOOLS_SCM_PRETEND_VERSION` defined when a tag doesn't yet exist.  Secondly, it is helpful to pass the CI environment flags so that the build script can adapt accordingly.  
One such item is the need to re-install build dependencies when in the Docker GitHub Action of `python-semantic-release`, you …
=> feat: provide limited parent context environment to `build_command`

action.sh, action.yml
Fix an issue introduced in `9.7.0` where `git_commiter_email` & `git_commiter_name` were not passed on through to PSR when using the GitHub Action
Resolve: #918
The `GIT_COMMIT_AUTHOR` variable was not exported or created in the environment which caused PSR to use the configuration file and/or default semantic-release values.  It was accidentally removed during the refactor as it was not obvious of its use.
Using my test project, [psr-test-gha](https://github.com/codejedi365/psr-test-gha), I was able to successfully release with the configuration defaults when no default is given and then commit with custom provided values.
=> fix(gha): fix missing `git_commit_author` definition in action

CONTRIBUTING.rst, pyproject.toml
Hi there,
I was unsure, why the build version is pinned to such an old version. Is there a reason?
What do you think about also adding `build[uv]` and using `python -m build --installer=uv .`?
Ref: https://build.pypa.io/en/stable/#python--m-build---installer
=> chore: bump build version in pyproject.toml and contributor guide

docs/configuration.rst, semantic_release/cli/commands/version.py, semantic_release/cli/config.py, tests/command_line/test_version.py
- Add the ability for the user to configure the set of environment variables to pass to the build command subprocess
- Resolve #922
Primarily to be good stewards of the provided authentication tokens to PSR, we do not blindly pass the entire parent process environment on to the child process of the build.  However, as #922 mentioned, there is a legitimate need to pass some user-defined environment variables on to the `build_command` child process.  This happy median is to provide a `build_command_env` configuration option that will handle definitions of either hardcoded values or variables desired to be passed along to the subprocess.
Added a separate cli test with a `pyproject.toml` configuration that included all the ways users can provide an environment variable.  We allow direct pass …
=> fix: enable user configuration of `build_command` env vars

action.sh
The github action doesn't translate the prelease_token option from the action.yml into the corresponding command line parameter. 
Add the parameter to ARGS in action.sh.
=> add prelease-token in github action.sh

docs/configuration.rst, semantic_release/cli/commands/version.py, semantic_release/cli/config.py, tests/command_line/test_version.py
Provide a flag in the configuration to disable git hooks that are present in the repository that might prevent `semantic-release version` from completing successfully.
This commit adds the configuration option, `no_git_verify`, that toggles the addition of `--no-verify` command line switch on git commit operations that are run with the `version` command.
=> feat(version-cmd): add toggle of `--no-verify` option to `git commit`

action.sh
- Applies digital signatures to tags created by the PSR GitHub Action
- Resolves: #936
We already configure provided SSH keys for signing the commits that are written by PSR in the GitHub Action but it was not applied to the tag's as the configuration setting was missing.  This PR updates the configuration to apply the signature to any tags created within PSR's GitHub Action (Docker).
User tested in their environment when modifying their action to point at this PR's base branch. Confirmed in issue.
=> feat(gha): configure ssh signed tags in GitHub Action

semantic_release/hvcs/github.py, semantic_release/hvcs/gitlab.py, tests/unit/semantic_release/hvcs/test_gitlab.py
- Improve Gitlab interface implementation to handle previously defined release & update it
- Improve overall unit testing for HVCS
Brings GitLab more in line with the features of GitHub to be able to edit a previous release's notes via the `changelog` subcommand.
I also found that with the switch to using `example.com` as the domain there were more errors in the test suite as I would receive a 404 that would cause testing to fail.  Clearly this means we were actually touching the real gitlab so I mocked out those appropriately.
I tested manually with a project access token on my local machine with a gitlab project. I first ran the pipeline to create a release normally and then used `semantic-release changelog --post-to-release-tag v1.0.0` to update the release notes with a new template. …
=> feat: extend gitlab to edit a previous release if exists

semantic_release/commit_parser/token.py
The default template can result in mixed (UNIX / DOS style) carriage returns in the generated changelog. Use a string replace in the commit parser to strip the DOS CRs ("\r"). While it's possible to do the replacement in the template, IMO, this is the better / correct way to fix it.
I checked, and seems like maybe it's only needed when we're _not_ doing a byte decode (so the case where `m` is a raw string)? I can add it back to both if you'd like, though.
Fixes #955
Note: this may result in some diffs in generated changelogs.
See also #952 
I'm happy to adjust existing tests in a way that would catch this and / or add a new test if someone can give me a general pointer on the best way / best place to do this. Also feel free to suggest a terser or more idiomatic way to do this.
=> fix(commit_parser): strip DOS carriage-returns in commits

.github/workflows/pr.yml, .pre-commit-config.yaml, docs/configuration.rst, pyproject.toml, semantic_release/cli/commands/publish.py, semantic_release/cli/config.py
Note: the current `ruff` pre-commit checks check `.`, however, there are multiple existing errors. Maybe it would make sense to switch `ruff` to run on changed files only unless `--all-files` is passed? That would be gentler, especially if we're not requiring all these checks to pass (that said, #958 has some misc fixes that resolve _some_ of the outstanding flagged and non-ignored issues).
- Update pre-commit hooks
- Switch away from deprecated flag to `ruff`
- Resolve two minor pre-commit hook findings
Note: I still see the following finding from `mypy`:
```
semantic_release/cli/commands/publish.py: note: In function "publish":
semantic_release/cli/commands/publish.py:66:9: error: "HvcsBase" has no
attribute "upload_dists"  [attr-defined]
hvcs_client.upload_dists(tag=tag, …
```
=> chore: update pre-commit hooks

.github/workflows/main.yml, .github/workflows/pr.yml, pyproject.toml, semantic_release/cli/commands/cli_context.py, semantic_release/cli/commands/version.py, semantic_release/cli/config.py, semantic_release/commit_parser/_base.py, semantic_release/hvcs/bitbucket.py, semantic_release/hvcs/gitea.py, semantic_release/hvcs/github.py, semantic_release/hvcs/gitlab.py, semantic_release/hvcs/remote_hvcs_base.py, semantic_release/version/algorithm.py, tests/command_line/conftest.py, tests/command_line/test_changelog.py, tests/conftest.py, tests/unit/semantic_release/hvcs/test_gitlab.py, tests/util.py
Having the `--diff` flag in `ruff check` seems to suppress failures from happening in CI. Remove the `--diff` flag, and then ignore or adjust to resolve the remaining `ruff` failures. This will help prevent new ruff errors from going unnoticed and getting checked in, at the expense of a little bit of clutter in the code.
Note: this can be merged with the two atomic commits, or squashed as one.
We should probably do this after #957 goes in (may require a little conflict resolution on one file)
=> chore: re-enable ruff warnings

.pre-commit-config.yaml, pyproject.toml, semantic_release/cli/commands/version.py, semantic_release/commit_parser/_base.py, semantic_release/commit_parser/scipy.py, tests/command_line/test_changelog.py
Here's another small one; let me know what you think:
- Remove `blacken-docs` in pre-commit config.
- Set `docstring-code-format` to `true` for ruff.
- Resolve `blanket-type-ignore` pre-commit check by adding types to mypy type ignores
Basically, [this](https://github.com/astral-sh/ruff/pull/8854) replaces what `blacken-docs` would have done.
Note: if you don't care about the type ignores, I can remove that check (`python-check-blanket-type-ignore` from https://github.com/pre-commit/pygrep-hooks, with or without reverting those annotations). Note: that check will run for users who have pre-commit setup / installed, but not for other users, so it's not enforced in CI, which is probably part of how these 3 ended up here.
=> chore: switch to ruff doc formatting and add ignore types

.pre-commit-config.yaml, pyproject.toml, semantic_release/cli/commands/version.py, semantic_release/commit_parser/_base.py, tests/command_line/test_changelog.py
As discussed in https://github.com/python-semantic-release/python-semantic-release/pull/964#issuecomment-2208080852, this will check for explicit error types in type ignores.
- Set `ignore-without-code` in mypy settings 
- https://mypy.readthedocs.io/en/stable/error_codes.html#requiring-error-codes
- https://docs.astral.sh/ruff/rules/blanket-type-ignore/
- Remove `pygrep` rule in pre-commit config to avoid flagging it twice locally (since there's a mypy pre-commit config already)
Tested locally that this should flag the case where the error type is not set.
=> chore: set `ignore-without-code` for mypy

semantic_release/changelog/release_history.py
- Improve performance of PSR when working on large git repositories
- Prevent ordering issues that arise from automated commit messages within milliseconds
Refactoring comparison data into a lookup datastructure allows for `O(1)` time lookups rather than `O(n)` searches on repositories with lots of tags.
Manually through the evaluation of logs, where many logs were not printed and it was noticable the number of iterations in the loops.  I did not do a benchmark datapoint though.
Run on PSR itself as it has enough tags to cause a slowdown and many irrelevant log entries.
```sh
semantic-release changelog
```
=> perf: improve git history processing for changelog generation

semantic_release/cli/cli_context.py, semantic_release/cli/commands/version.py, tests/command_line/test_main.py, tests/command_line/test_version.py
- Remove unnecessary prerequisite release branch match when irrelevant to use
- Resolve #900
When using PSR to evaluate what the last released tag was, it is irrelevant to impose release branch restrictions on the usage as it doesn't matter what branch you are actually on.  `--print` and `--print-tag` are not included here as those determine the next version value and those do currently rely upon the release branch configuration.
Created test cases that evaluate non-release branch environments in regular or strict mode while using `--print-last-released`, `--print-last-released-tag`. The tests also evaluated the same command when in a detached head state.
=> fix: enable `--print-last-released*` when in detached head or non-release branch

docs/configuration.rst
`git_committer_name` was repeated; replace one instance of it with `git_committer_email`
=> docs: update GHA parameter name for commit email

docs/changelog_templates.rst, docs/configuration.rst
Improve clarity of documentation after more than one proposed bug related to `changelog_file` vs `template_dir` unexpected results.
=> docs: clarify changelog file usage

pyproject.toml, tests/command_line/test_changelog.py, tests/command_line/test_version.py, tests/scenario/test_next_version.py, tests/scenario/test_release_history.py, tests/unit/semantic_release/cli/test_util.py, tests/unit/semantic_release/hvcs/test__base.py, tests/unit/semantic_release/version/test_declaration.py
pytest_lazyfixture is unmaintained and not compatible with Pytest 8
it is being removed from distributions
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1076459
I packaged this for Debian right now.
https://salsa.debian.org/python-team/packages/python-semantic-release/-/pipelines/705005
=> replace pytest_lazyfixture with pytest_lazy_fixtures.lazy_fixture

docs/configuration.rst
While reading the [configuration](https://python-semantic-release.readthedocs.io/en/latest/configuration.html) page in the docs, I was reading the [build_command](https://python-semantic-release.readthedocs.io/en/latest/configuration.html#build-command) section and noticed that the table describing the the environment variables on Windows systems was corrupted.
This PR fixes that issue so that the table is rendered correctly.
I suspected it was likely a whitespace / newline issue, because reStructuredText depends on delineation between elements for the parser to identify those elements.  When I located the source for this content I expected to find a paragraph element with the text `In addition, on windows systems these environment variables are passed:` followed by the markup for a …
=> docs(build_command): Add newline to fix table rendering

docs/automatic-releases/github-actions.rst, docs/github-action.rst, pyproject.toml, scripts/bump_version_in_docs.py
It's generally a good practice to anchor / pin GHA workflows. This updates the existing examples to make that more clear.
Fixes #1003
=> docs: use pinned version for GHA examples

semantic_release/cli/changelog_writer.py, semantic_release/cli/commands/changelog.py, semantic_release/cli/commands/version.py
- Provide the `context.history` variable to release notes generation
- Resolves: #984
Temporarily return the `context.history` variable to release notes generation as many users are using it in their release documentation. It was never intended to be provided and will be removed in the future.
Context was removed in `v9.8.3` during a refactor and condensing of changelog and release notes functionality. Ends up the context was provided accidentally because of variable re-use rather than explicit definition which is why it broke upon refactor.
Performed some manual testing with a custom template upon the PSR repository.  See the commands below for replication. The importance is that the release notes was printed to the console using `--noop` mode so we are sure that the formatting and use …
=> fix: provide `context.history` global in release notes templates

docs/automatic-releases/github-actions.rst, docs/github-action.rst, pyproject.toml
- Update the docs' examples to the latest version
- Ensure the docs modifications are included in the version commit
- Noticed after the #1010 issue that I forgot to add the files into the index to be included after the version was bumped.
- Since the docs weren't updated last version, must include that manually.
Ran the version command locally to ensure that when the build command was executed the resulting docs files were staged in the index prior to commit.
```sh
semantic-release version --no-commit --no-tag --no-changelog
git status
```
=> chore: fix failure to commit doc example version bumps

semantic_release/cli/config.py
- Resolves: #994, the bug that appeared on windows because of `pathlib.Path.resolve()` differences of implementation
- Solution provided by @wiley-black
=> fix: fix path traversal detection for windows

docs/conf.py, semantic_release/cli/commands/version.py, semantic_release/hvcs/gitea.py, semantic_release/hvcs/gitlab.py, semantic_release/hvcs/util.py
- set `ignore-module-all` for `autodoc_default_options` to resolve some Sphinx errors about duplicate / ambiguous references https://github.com/sphinx-doc/sphinx/issues/4961#issuecomment-1543858623
- Standardize some non-standard (Google-ish) docstrings to Sphinx format, to avoid ruff and Sphinx arguing about underline length.
- Fix indents and other minor whitespace / formatting changes.
Fixes #1029
Happy to do this differently, but Sphinx style seemed to match most of what we had in the codebase
Pros:
* Types are inferred automagically
* A bit easier for machine parsing
* Slightly smaller footprint
Cons: 
* A bit harder to read directly in the code (no types, etc.)
* [No ruff support](https://github.com/astral-sh/ruff/issues/6606) for setting `pydocstyle` to `sphinx`.
Generated locally …
=> docs: update docstrings to resolve sphinx failures

.github/workflows/pr.yml
- Limit the amount of unimportant jobs the CI does
I was able to use a file changes detection action that would distinguish what files changed on a PR and subsequently use conditional statements to turn off the long testing jobs (windows) when it was not relevant.  This is obvious when you have a bunch of documentation changes but then the CI would run the entire test suite even though no source code or test code was touched.
I determined to break up the parts of the repository into a few categories: build, ci, doc, src, & test.  A less than obvious choice I made but the rationale was to include `pyproject.toml` in the list of source code files because this is the file in which the dependencies are defined.  The dependencies might as well be a part of the source as it will be when at …
=> ci(pr): add file type filter to regulate testing jobs

docs/configuration.rst, pyproject.toml, semantic_release/cli/config.py, tests/command_line/conftest.py, tests/conftest.py, tests/scenario/test_version_stamp.py
- Provides some flexibility of `version_variables` results that can work across multiple languages easily 
- Resolves: #601
- Resolves: #706
- Resolves: #962
- Resolves: #1026
Previously json would not work due to the key being wrapped in quotes and therefore the regex would not match
The previous generated regex also has issues with yaml when it does not usually use quotes. The regex originally only wrapped the version to be replaced in quotes (for example: `version = "1.2.3"`) but now both the key and version can optionally be wrapped in different kind of quotations.
I also ended up adding a small negative lookbehind to make sure that our pattern matcher did not match on suffixes of other variable names (ex. `cff-version`).
I tested json with a single key of the word `version` which was …
=> fix(version): increase `version_variable` flexibility w/ quotes (ie. json, yaml, etc)

.github/workflows/pr.yml
- Further minimize unnecessary pipeline delays & actions consumption
I realized that using the glob syntax actually would cause a change in the `stale.yml` or the `main.yml` workflows would cause a PR to execute everything. That doesn't make sense so I limited it to just the `pr.yml` workflow scope.
=> ci(pr-workflow): limit which workflow files trigger full testing

.github/workflows/main.yml, .github/workflows/pr.yml
- Removes beautify job & enforces standards via lint job instead
The main problem here is that if you merge two PRs to main too quickly (now that tests run 15min) it will cause beautify
to fail in the first job which could prevent a release if it was intended to be released.  We shouldn't be reformatting
the code automatically in the pipeline anyway (as you should limit the amount of automatic writes to the repository) so
instead use the pipeline as a check which will eliminate the concurrency problem.
=> ci: remove beautify but enforce formatting standards via lint

.github/workflows/main.yml
- Adds moving partial version reference tags automatically upon release
In order to have GitHub Actions auto update an action, there needs to be a partial version tag.  These two steps will automatically update a partial minor version and also a partial major tag as python-semantic-release creates a release.
ex. `v9.8.9` is released, and then the `v9.8` and a `v9` tag are moved to reference the same release.
I ran the script code locally in a script file. I used the same global variables that would exist in the CI.  The script I used is below.
```bash
#!/bin/bash
set -e
FULL_VERSION_TAG="$(git tag --list --sort=-v:refname | head -n1)"
echo "Last version tag: $FULL_VERSION_TAG"
MINOR_VERSION_TAG="$(echo "$FULL_VERSION_TAG" | cut -d. -f1,2)"
echo "Minor version tag: $MINOR_VERSION_TAG"
git …
```
=> ci(main-workflow): add steps to update partial version reference tags

.github/workflows/main.yml, docs/automatic-releases/github-actions.rst
- Resolves release when workflows are backed up and might release on a new HEAD of main not tested
- Updated the example docs to prevent others having this issue
This happened for the release of `v9.9.0`.  I merged 3 PRs within a short time and since the tests were still running I thought I prevented the actual release commit pipeline from running but then the previous pipeline released the new code anyway because it pulled from the branch when the branch had moved during the workflow execution.
Unfortunately I won't be able to test this until it happens again.  This should fix any issues as it is what I would do manually.
=> ci: fix release on moved main

.github/workflows/main.yml
- Ensures that file changes look at previous push to current head
I had to review the github action again to make sure how the push event would be handled as opposed to the PR event.  I needed to make sure that first the commit would exist with the different fetch depth but then also make sure that we specified the base sha of where it was prior to this latest push.  You can't just do a fetch depth of 2 in the case you used the GitHub PR resolution `Rebase and Merge` as it may be more than 1 commit that is all pushed at once.
Unfortunately, not much to test other than doing it live as its hard to replicate the environment within github actions
=> ci(main-wkflow): ensure file changes are only detected from last push to current HEAD

.github/workflows/main.yml
- Update this project to be inline with our documentation
- Remove the deprecated action
Because we renamed the action we needed to update the implementation in our project as well.  As many people will use our project as a reference.  
Not merging this immediately until after the next release is also a slight test for making sure that our warning annotation works for `upload-to-gh-release` as we should see it in our Actions summary.  Then we will change it over to the new action version.
Just considered that the name change doesn't need testing.  I can confirm that the GitHub Actions VSCode plugin successfully located the new name and since it is the same code base, it just work out the box.
=> ci(main-workflow): change `upload-to-gh-release` action to `publish-action@v9.9.0`

tests/command_line/test_main.py, tests/fixtures/git_repo.py
- Update testing configurations since git also supports tag signing configs
While working on another repository, I realized that you can not only set `commit.gpgsign = true` but you can also set `tag.gpgsign = true`.  We previously identified in this project during testing these cause errors not only in the CI but locally as you can't provide a password if this feature is tripped.  Therefore in all of our example environments we must turn off the `gpgsign` configuration explicitly.  
This PR adds the configuration to turn off tag signing in the local repository.
Set your global configuration to have all tags automatically signed and then try to run the test suite. Since the test suite pulls from your global git configuration as the default, the local repo will try to sign tags during the …
=> test(repos): adjust git config in example repos to prevent autosigning

action.sh, action.yml, docs/automatic-releases/github-actions.rst, docs/commands.rst
- Enable the user to toggle the `--skip-build` option on PSR in the github-action
=> feat(github-actions): add an action `build` directive to toggle the `--skip-build` option

.github/workflows/main.yml
- Correct the mistake I had releasing v9.10.0 where it crashed after semantic-release was completed
I wanted to have some git commands run after the release to create some moving short reference tags and ends up in the CI git is not configured. Because of that when I tried to do a `git tag` it failed and complained about no name or email.  This corrects that issue by setting the environment variable for the committer information.  I tested this on my own fork and it released successfully.  Oddly enough, I tested just the GIT_AUTHOR_{NAME,EMAIL} vars and it fails but if you have GIT_COMMITTER_{NAME,EMAIL} by itself it is fine.
Ran multiple releases on my fork as I could reverse it immediately. I probably should of done that when I initially made the change instead of hoping it would work. …
=> ci(main-wkflow): fix unknown git user before tag creation

semantic_release/cli/config.py, tests/unit/semantic_release/cli/test_config.py
Resolves #931 
No regex validation is currently done in branch configs, causing an obscure error from the `re` library when the regex fails to compile. This is not obvious to the user what the error is, nor does it give any indication of how to fix it.
This is especially a problem when `match="*"`, which a user would expect to match all branches, but fails to match anything and throws this error because the plain wildcard is not a valid regex.
Pydantic field validation is often the correct place to validate inputs because it keeps logic simpler in other places. 
Validating a regex is easiest by trying to compile it and catching any exceptions, hence that check.
The plain wild card `"*"` is common enough an idiom where although it is not a valid regex, its intent is clear, and supporting …
=> fix: Validate branch config regex matches and allow plain wildcards

semantic_release/changelog/release_history.py, semantic_release/cli/commands/main.py, semantic_release/commit_parser/angular.py, semantic_release/commit_parser/emoji.py, semantic_release/commit_parser/scipy.py, semantic_release/commit_parser/tag.py, tests/command_line/test_version.py
- Forces any commits that cause a version bump to always be included in the changelog
This seems a bit counter intuitive as it goes against what the user has configured but it makes sense to avoid the situation where their is a legitimate breaking change in a different commit type that generally is ignored but because it is breaking then it must be included so that the changelog is not empty.  Example: deprecating support for an older python version.  Generally I categorized that under `refactor` however generally I don't show that in the changelog and it would be filtered out however it came with a breaking change which causes the version bump.  This change forces it to be included otherwise the changelog was empty for the version bump which is definitely not correct. 
At first I only …
=> fix(changelog): ignore commit exclusion when a commit causes a version bump

.github/workflows/stale.yml
- Add an additional tag that is exempt from stalebot stale labels or needing updates as `confirmed` doesn't make sense for these
Issues like the next breaking version or long term issues/announcements (like python 3.7/3.8 deprecation annoucements) should not be closed for being stale or require periodic updates.  They will last for a long time likely more than the 2-3 months allotted in those categories.
=> chore(stalebot): add `info` tag that is exempt from being stale or needing updates

.github/workflows/cicd.yml
- Separate out deployment from release jobs in pipeline
It is better design to have a separate deploy job rather than one job to release and deploy because if your deployment fails for some reason (auth token or other mishap) then you have a release tag on the repository but no distribution artifact. Normally you might just update the auth token but this time you have to reverse most of the release job to do it again rather than just re-running the deployment.  I have also found this reigns true if you have multiple deployment locations. You should have each deployment location as a separate job so they can independently fail (and not prevent others) and you can re-deploy (via job re-run) them individually if needed.  It can be difficult to republish as most registries will fail if it has …
=> ci(cicd-wkflow): separate deployment from release job to enable job re-runs

pyproject.toml
- Update the build dependencies
Bumping setuptools up to the latest version before they removed support for `python 3.8`. Since we still support `3.8` for the meantime, this is as high as we go.
=> build(deps-build): update setuptools requirement from ~=69.0 to ~=75.3.0

src/semantic_release/data/templates/angular/md/.release_notes.md.j2, tests/e2e/cmd_changelog/test_changelog.py, tests/unit/semantic_release/changelog/test_release_notes.py
- Automatically adds a comparison URL to the release notes
Its a common item to add to the release notes is a comparison URL to the previous version that was released. This adds it to the default release notes template.
Updated the release notes template unit test which has more than one release tested.  It also is tested through the changelog command with the `--post-to-release-tag` option and luckily it caught the edge case of when you are trying to use PSR to update the release notes of an earlier release and it happens to be the very first one.
=> feat(release-notes): add tag comparison link to release notes when supported

src/semantic_release/changelog/release_history.py, src/semantic_release/commit_parser/token.py, tests/e2e/cmd_changelog/test_changelog_custom_parser.py, tests/util.py
- Resolves: #778
This adds an attribute to the ParsedCommit object that allows custom parsers to set to false if it is desired to ignore the commit completely from entry into the changelog.
=> feat(commit-parser): enable parsers to flag commit to be ignored for changelog

src/semantic_release/data/templates/angular/md/.components/changes.md.j2, src/semantic_release/data/templates/angular/md/.components/macros.md.j2, src/semantic_release/data/templates/angular/rst/.components/changes.rst.j2, src/semantic_release/data/templates/angular/rst/.components/macros.rst.j2, tests/unit/semantic_release/changelog/conftest.py, tests/unit/semantic_release/changelog/test_default_changelog.py, tests/unit/semantic_release/changelog/test_release_notes.py
- Improve ease of reading changelog with many adjustments
This is more of an aesthetic component to make the changelog easier to read. When run an alphabetical sort on the different changes then it automatically will group like values together. This is very helpful when people use pre-defined or common scope values which consolidates those updates.  Conversely if you have a mixture of scoped and non-scoped commits, it will lay out all the non-scoped commits first (which generally mean they cover a larger subset of the project) before the smaller more specific changes are listed.
Adjusted the fake release history fixtures to provide a non-alphabetical ordering to commits and then force it to comply with the resulting test that is in a set order.  This ensures the commits were in fact …
=> feat(changelog): alphabetize commit summaries & scopes in default templates

src/semantic_release/data/templates/angular/md/.components/changes.md.j2, src/semantic_release/data/templates/angular/md/.components/macros.md.j2, src/semantic_release/data/templates/angular/md/.release_notes.md.j2, src/semantic_release/data/templates/angular/rst/.components/changes.rst.j2, src/semantic_release/data/templates/angular/rst/.components/macros.rst.j2, tests/fixtures/git_repo.py, tests/unit/semantic_release/changelog/conftest.py, tests/unit/semantic_release/changelog/test_default_changelog.py, tests/unit/semantic_release/changelog/test_release_notes.py
- Adds clarity for what changes the user must be aware of when bumping to the next major version
- Resolves: #244
This is more of a stepping stone to the next phase where we will drop the need to display the entire commit in the changelog. The Breaking change descriptions are one of the items we didn't display normally even though it was parsed.
I updated the git repo changelog generator for the E2E scenarios which means the E2E tests that validate changelogs have the correct breaking change summaries included.
I also updated the release notes and changelog template test cases to separate out the breaking change descriptions into their own section and validate the template provides the accurate result.
1. Checkout this pr
2. Reset by 4 commits to remove the fix
3. Run pytest to see the …
=> feat(default-changelog): add a separate formatted breaking changes section

src/semantic_release/__main__.py
- Adds a helpful debug message when fatal errors occur
Ever since I added the exception catch and display of an error message I felt that people might not know what to do instead without me telling them to when they report the issue.  This helps elevate that.
Manually validated the message returns correctly via the steps to verify. I did not think it was necessary to automate this piece as we don't mess with the `__main__.py` very much.
1. Check out this PR
2. Modify src/semantic_release/cli/commands/main.py and add `raise Exception` at the bottom of the file.
3. Execute `semantic-release changelog` and you will see the error and a recommendation
4. Execute `semantic-release -vv changelog` and you will see the stacktrace and error without any recommendation.
=> fix(cli): add error message of how to gather full error output

src/semantic_release/cli/commands/version.py, src/semantic_release/gitproject.py
- Controls date that is defined by the release tag
Ultimately this is more to just control the datetime of a tag deliberately as we are doing the same for the commit action.  This also very much helps testing as we can control the datetime from within the test cases as well which is very necessary to ensure changelogs and stable dates for whenever the automated pipelines execute.
=> fix(cmd-version): force tag timestamp to be same time as release commit

src/semantic_release/changelog/template.py
- Trims the resulting templates to a single newline at end of a file
I came across this problem when doing some testing of the rebuild repo tests where the changelog would have a random extra newline.  This resolves that.
The new rebuild tests will validate this when the tests actually work because the changelogs that are generated match the changelog build through the test code.
=> fix(changelog): ensure user rendered files are trimmed to only a single ending newline

.github/workflows/ci.yml, src/semantic_release/version/algorithm.py, tests/e2e/cmd_version/bump_version/trunk_based_dev/test_repo_trunk_dual_version_support.py, tests/e2e/cmd_version/bump_version/trunk_based_dev/test_repo_trunk_dual_version_support_w_prereleases.py, tests/fixtures/git_repo.py, tests/fixtures/repos/trunk_based_dev/__init__.py, tests/fixtures/repos/trunk_based_dev/repo_w_dual_version_support.py, tests/fixtures/repos/trunk_based_dev/repo_w_dual_version_support_w_prereleases.py, tests/unit/semantic_release/version/test_algorithm.py
- Refactors the version incrementation algorithm to handle prereleases & official releases when supporting more than the latest major release
- Resolves: #861
This change implies that where ever you are releasing from within the repository, the only tags you know about are the ones in your direct history line.  This means that prereleases of older versions can be created which were not possible as documented in #861.  Official releases were possible of older versions but this maintains that implementation.
I added 2 more repo rebuild tests that demonstrate and validate the use of PSR for a dual version support environment of both official releases and prerelease variants of the last major version (after the latest major version has been released).
Note that the rebuild repos will need to …
=> fix(algorithm): enable maintenance prereleases

src/semantic_release/cli/config.py, tests/e2e/cmd_config/test_generate_config.py
- Resolve #1123
Similar to the previous error with windows (#994), resolution must take place to make absolute paths and then be able to validate them against one another. I didn't previously run `resolve()` on the found repo directory so it would display a symlink like alias of the home drive.  When the changelog parents were evaluated, the changelog file was fully resolved to the network share that it represented, which caused the error to be thrown.
The issue reporter tried the fix manually and it seemed to work. I modified our generate configuration tests to also load the configuration and run `semantic-release --noop --strict version --print` which should load the configuration fully and then attempt to evaluate the repository. If any of that fails then it will throw an error.  This …
=> fix(config): ensure default config loads on network mounted windows environments

docs/automatic-releases/github-actions.rst
- Updates the examples in the documentation to point at the latest version of PSR
This used to be automatic until I had switched around the CI to build at the beginning of the workflow and then not build upon release (so that the tested artifact was indeed the item that was released).  This however meant that the documentation was failing to be updated upon release.  This PR gets it back up to the latest.  The next PR (#1141) makes this process automated again
=> docs(github-actions): update PSR versions in github workflow examples

src/semantic_release/helpers.py
- Avoids any issues with dynamic importing given a file name with parent path traversals
The dynamic import originally would just replace "/" with "." to make the import module name more pythonic, however this would be problematic in monorepos which would use "../../misc/commit_parser.py" to locate the parser and so the resulting `sys.modules` entry would have numerous periods (.) as a prefix. This removes that possibility. Still always an issue if the imported module name matches an existing module but the likelihood is low.
Used my codejedi365/psr-monorepo-poweralpha repository to test a custom monorepo parser and release
=> fix(parser-custom): handle relative parent directory paths to module file better

docs/changelog_templates.rst, src/semantic_release/changelog/context.py, src/semantic_release/cli/changelog_writer.py, src/semantic_release/commit_parser/angular.py, src/semantic_release/commit_parser/emoji.py, src/semantic_release/commit_parser/util.py, src/semantic_release/helpers.py, tests/unit/semantic_release/changelog/test_changelog_context.py, tests/unit/semantic_release/changelog/test_release_notes.py, tests/unit/semantic_release/test_helpers.py
- Add `sort_numerically` to the changelog context as a jinja filter
This helps organize PR or issue numbers in true numerical order even if they are a string with some alphanumeric or symbol as a prefix value.  
Added unit test to validate all the ordering of values at the function level. Then I added unit tests to the release notes and changelog context validators to ensure that the function works and is available in the jinja environments.
```sh
git fetch pull/1146/head:pr-1146
git checkout --detach pr-1146~3
pytest -vv -k test_sort_numerically
pytest -vv -k test_changelog_context_sort_numerically
pytest -vv -k test_release_notes_context_sort_numerically_filter
git merge pr-1146
pytest -vv -k test_sort_numerically
pytest -vv -k test_changelog_context_sort_numerically
pytest -vv -k …
```
=> feat(changelog): add `sort_numerically` filter function to template environment

src/semantic_release/changelog/release_history.py, src/semantic_release/changelog/template.py, src/semantic_release/cli/commands/version.py, src/semantic_release/cli/masking_filter.py, src/semantic_release/version/algorithm.py
- Remove extra debug statements
It ends up most people run the CI in very verbose (`-vv`) mode because its hard to debug in an ephemeral environment. Unfortunately, PSR had some debug statements that really don't provide much value and end up just cluttering the output log. I got rid of those and then validated the rest of the logs messages are helpful and should be at the designated level or not.
=> perf(logging): remove irrelevant debug logging statements

Dockerfile
Permission issues can occur on the Python bytecode files as the container entrypoint is being run as the root user. When e.g. using a custom parser the bytecode file will be owned by the root user instead of the user running the action.
This can cause subsequent steps to fail.
For example when running actions/checkout after python-semantic-release it will try to do a `git clean -ffdx` which will fail to remove the pyc file.
This could probably also be avoided by running the entrypoint as a non privileged user, but this would require using sudo or alternative solutions for running e.g. the `git config --system` command.
In general the usage of the root user isn't really a problem for this action so this seems to be the most straightforward way to workaound the permission issues.
- Defined …
=> feat: Disable writing Python bytecode

src/semantic_release/cli/config.py, src/semantic_release/hvcs/_base.py, tests/unit/semantic_release/cli/test_config.py, tests/unit/semantic_release/hvcs/test__base.py
- Add support for git insteadOf configuration for repository origin
- Resolves: #1150
Previously, python-semantic-release would attempt to use the raw url from
the repository configuration (`me:myproject` in the above example), and
would fail to parse it because it's not actually a url. With this change,
psr instead calls out to `git remote get-url`, which fully expands any aliases via git.
[1]: https://git-scm.com/docs/git-config#Documentation/git-config.txt-urlltbasegtinsteadOf
Created a unit test that will modify a git configuration with a remote origin defined with an alias and the associated alias defined separately.  The runtime context is loaded and then validated through the GitHub VCS client.
```sh
git fetch pull/1151/head pr-1151
git checkout pr-1151~1 --detach
pytest -vv -k …
```
=> fix: Deal with remote urls aliased using insteadOf directives

scripts/bump_version_in_docs.py
Simplify adding doc statements for when a feature is introduced
Previously I would have to monitor which version was going to be released to make sure the docs would state when a feature was introduced. This change makes it automatic to replace key variables in the docs.
Manual execution of script
=> chore(scripts): extend stamping to all docs with $NEW_VERSION & $NEW_RELEASE_TAG vars

docs/configuration.rst, src/semantic_release/version/declaration.py, src/semantic_release/version/declarations/pattern.py, tests/e2e/cmd_version/test_version_stamp.py, tests/unit/semantic_release/version/declarations/test_pattern_declaration.py
As discussed in https://github.com/python-semantic-release/python-semantic-release/issues/1156 and https://github.com/python-semantic-release/python-semantic-release/issues/846, this adds two features to the version_variables configuration:
1. allow the @ separator between the search string and the version within the files
2. allow a single "v" without any spaces to precede the version
E.g. when running psr with the following configuration
```toml
[tool.semantic_release]
version_variables = ["my-versions.txt:version"]
```
and there is a `my-versions.txt` with content
```
version@v1.2.3
```
and the new version is `2.3.4` the content of `my-versions.txt` will be:
```
version@v2.3.4
```
Simple adaption of the regex did the trick
Unittesting was not easy as the implementation was entangled …
=> config, version_variables: allow @ as separator and v to precede the version

pyproject.toml, tests/e2e/test_main.py
- Adds support for default implementation of `uvx` which matches script name with package name.
- Resolves: #1195
---
=> feat: add package name variant project script

docs/automatic-releases/github-actions.rst
extends the github-actions monorepo documentation
I followed the monorepo approach for configuring the github-actions workflow setting a specific directory for the build. I did not update the configuration in the pypi publish action, thus running into an error. With the fix provided this error could be resolved.
1. Not passing the packages-dir line in the workflow >> FileNotFoundError: [Errno 2] No such file or directory: '/github/workspace/dist'
2. Adding the configuration >> passed successfully
https://github.com/marketplace/actions/pypi-publish#customizing-target-package-dists-directory
-
---
=> docs(github-actions): add packages-dir configuration in monorepo example

src/semantic_release/hvcs/remote_hvcs_base.py, tests/unit/semantic_release/hvcs/test_bitbucket.py, tests/unit/semantic_release/hvcs/test_gitea.py, tests/unit/semantic_release/hvcs/test_github.py, tests/unit/semantic_release/hvcs/test_gitlab.py
- The change adjusts the url normalization computation to remove any path prefix and only the path prefix even when letters are shared with the rest of the url path.
- Resolves: #1204
---
=> fix(changelog-filters): fixes url resolution when prefix & path share letters

pyproject.toml
- Prevent breaking change to test cases from click update
click 8.2 has a breaking change in the test suite where it removes a parameter from the cli runner. There is additional deprecation warnings included as well so for now since it will break our tests limit this to 8.1.0 only.
Verified the CI passed both the mypy lint step and the E2E tests worked.
---
=> build(deps): prevent update to `click@8.2.0`

docs/configuration.rst, src/semantic_release/version/declarations/pattern.py, tests/unit/semantic_release/version/declarations/test_pattern_declaration.py
- Adds the feature to stamp when the variable uses `==`.
Needed to add a feature in order to stamp into `requirements.txt` for when PSR will update its Github Action dependencies definition which I needed to be in the `pip freeze` format of `requirements.txt`.
Added a unit test to verify that a version definition with `==` will be updated with a new version.
---
=> feat(cmd-version): enable version stamp of vars with double-equals operand in `version_variables`

pyproject.toml
- Automates the bump of the GitHub action dependency when a new version is released.
With the refactor of the GitHub action Docker build, I changed it to actually download the published python-semantic-release package rather than just load the GitHub source code into the container. This ensures that we have less disparity between what users report errors as the runtimes are different.  We must now bump the version value in the `requirements.txt` that is used when building the GitHub Action when we bump the overall version.
Manually with the stamp only command to make sure the newly defined version is inserted into `src/gh_action/requirements.txt`
---
=> chore(conf): configure project to stamp ci action's `requirements.txt` w/ new version

CHANGELOG.rst, config/release-templates/.components/first_release.md.j2, config/release-templates/.components/macros.md.j2, config/release-templates/.components/macros.rst.j2
=> chore(changelog): update PSR template after v10 strips PR numbers from subject lines

.github/workflows/cicd.yml, .github/workflows/validate.yml, src/gh_action/action.sh
- Solves the issue with random file permissions errors after release
I found that here on PSR we had some issues writing the partial tags occasionally after PSR had created a commit. I discovered that this was because while in the Docker container, the commit action had turned certain files within the git repository (which is mounted into the container) to root owned files. Then afterword if the sha1 for the tag matched the first few characters of the sha1 of the commit then it would collide and fail with permissions errors on the `.git/objects/` folder.
I ran this on my repository fork with a full file listing of the `.git/` directory. I could see in comparison to when this project released to after this fix was implemented how the file ownership was corrected from `root:root` to …
=> fix(github-actions): add filesystem UID/GID fixer after action workspace modification

tests/const.py, tests/e2e/cmd_version/bump_version/github_flow/test_repo_1_channel_branch_update_merge.py, tests/fixtures/git_repo.py, tests/fixtures/repos/github_flow/__init__.py, tests/fixtures/repos/github_flow/repo_w_default_release_w_branch_update_merge.py
Provides a repo fixture to reproduce the problem described in https://github.com/python-semantic-release/python-semantic-release/issues/1252 (based on [this comment](https://github.com/python-semantic-release/python-semantic-release/issues/1252#issuecomment-2905368729)) 
Added a new repo following the examples in other fixtures.
Had to made one more addition: `simulate_change_commits_n_rtn_changelog_entry()` fixture always worked with the `file_in_repo`. For this specific flow it caused merge conflicts, because commit in the feature branch was made before default branch was merged into a feature branch. Made this parameter configurable.
I ran the test and it failed with the expected error (empty `## v0.3.0 (2025-05-31)` changelog entry)
```text
>           assert …
```
=> test(cmd-version): add fixture to reproduce issue with empty changelog

docs/configuration/configuration-guides/uv_integration.rst, docs/configuration/configuration.rst, src/semantic_release/cli/commands/version.py, tests/e2e/cmd_version/test_version_build.py
- Documentation fix on how to update the uv lock file after new release
- Resolves: #1280
- I am using `uv` and PSR for my package: https://github.com/aqib-oss/sonar-qube-gh-action
- I looked at the `uv` documentation and found a command to upgrade the version of only one package. Since `uv` lock file has the version of your project as well, I found that the command can be used to have the version synced in the lock file after PSR upgrades the version in `pyproject.toml` file.
I tested in my own repository where I observed the issue.
- `pyproject.toml` file for my repo: https://github.com/aqib-oss/sonar-qube-gh-action/blob/main/pyproject.toml
- Commit to show that the fix works: https://github.com/aqib-oss/sonar-qube-gh-action/commit/ee19420fe4cd1d379ddb6db37d4dcce8fb5176ea
Create a …
=> docs: uv integration lock file ver upgrade

README.rst
Hi, I noticed that the link in the documentation is no longer working.
---
=> docs: +1/-1 fix readme typo

docs/concepts/getting_started.rst
Fixes typo in getting started doc. Resolves: #1291
Solves issue by removing duplicate naming.
Simple change to docs only, built & examined web output using `sphinx-autobuild --open-browser docs docs/_build/html` as per contributing guidelines.
Follow `getting_started.rst` for a basic python package. Output should be
```
> semantic-release -v --noop version
🛡 You are running in no-operation mode, because the '--noop' flag was supplied
[23:57:33] INFO     Loading configuration from pyproject.toml                                                                                  util.py:77
branch 'main' isn't in any release groups; no release will be made
```
instead of 
```
> semantic-release -v --noop version
🛡 You are running in no-operation mode, because the '--noop' flag was supplied …
```
=> docs(getting_started.rst): Remove exclude_commit_pattern self-reference.

docs/configuration/configuration-guides/uv_integration.rst
This PR adds `--no-changelog` flag to build job as _CHANGELOG.md_ is not passed as an artefact to release job.
=> docs: do not update CHANGELOG.md on build command

src/semantic_release/cli/commands/version.py, src/semantic_release/cli/github_actions_output.py
- Resolves: #1315
Unfortunately, PSR introduced a bug in 10.3.0 when attempting to provide more CI outputs for GitHub Actions. It required our GitHub client interface to be loaded and even if it was not using GitHub CI to be run. This caused errors in Gitea and likely GitLab/Bitbucket environments. This change prevents that from happening but if any users pipelines were intentionally presenting the environment variable "GITHUB_OUTPUT" to enable action output to enable passing along internal outputs of PSR then their hack will no longer work after this change.
---
=> fix(cmd-version): prevent errors when PSR is executed in non-GitHub CI environments
