python-semantic-release/python-semantic-release

semantic_release/__init__.py
semantic_release/cli.py
semantic_release/defaults.cfg
semantic_release/errors.py
semantic_release/history/__init__.py
semantic_release/history/logs.py
semantic_release/history/parser_angular.py
semantic_release/hvcs.py
semantic_release/settings.py
tests/test_cli.py
tests/test_history.py
tests/test_hvcs.py
tests/test_parsers.py
tests/test_settings.py

[WIP] Add changelog generation

---

semantic_release/cli.py

```
Usage: cli.py [OPTIONS] COMMAND
Routes to the correct cli function. Looks up the command in the global
scope and calls the function. :param command: String with the name of the
function to call :param kwargs: All click options.
Options:
--major  Force major version.
--minor  Force minor version.
--patch  Force patch version.
--post   Post changelog.
--noop   No-operations mode, finds the new version number without changing
it.
--help   Show this message and exit.
```
```
Usage: cli.py [OPTIONS] COMMAND [ARGS]...
Options:
--major  Force major version.
--minor  Force minor version.
--patch  Force patch version.
--post   Post changelog.
--noop   No-operations mode, finds the new version number without changing
it.
--help   Show this message and exit.
Commands:
changelog
publish
version …
```

refactor: Refactoring cli.py to improve --help and error messages

---

docs/automatic-releases/index.rst
semantic_release/ci_checks.py
tests/ci_checks/test_circle.py

Add circle ci checks

---

semantic_release/cli.py
semantic_release/history/__init__.py
semantic_release/history/logs.py
semantic_release/vcs_helpers.py
tests/test_history.py

Add git hash to the changelog

---

requirements/base.txt

Change the Gitpython version number to fix a bug described in #80.

fix: change Gitpython version number

---

semantic_release/history/logs.py
tests/test_history.py

fix: Add commit hash when generating breaking changes

---

tests/ci_checks/test_checker.py
tests/mocks/__init__.py
tests/test_cli.py
tests/test_history.py
tests/test_pypi.py
tests/test_vcs_helpers.py

Adds some coverage mainly on cli and vcs_helpers

test: better test coverage

---

semantic_release/vcs_helpers.py

Partially addresses #109; tested by @AlphaMycelium

fix(github): add check for GITHUB_ACTOR for git push

---

semantic_release/cli.py
semantic_release/history/__init__.py
semantic_release/history/logs.py
semantic_release/history/parser_angular.py
semantic_release/history/parser_tag.py
semantic_release/pypi.py
semantic_release/settings.py
semantic_release/vcs_helpers.py
tests/test_vcs_helpers.py

Made various edits to improve the readability of code for newcomers to the project.
- Docstring changes
- Extra comments
- Small updates to some CLI output
I recommend squashing this into one `refactor` commit when merging.

Comments and readability improvements

---

docs/configuration.rst
semantic_release/defaults.cfg
semantic_release/history/logs.py

Customization of changelog can be done via changelog_sections var in configuration.
Fixes #193

Changelog sections customization

---

semantic_release/history/__init__.py

Use a `[=:]` group instead of running two separate searches.

Combine = and : into one regex

---

semantic_release/cli.py
tests/test_cli.py

Use getboolean for commit_version_number

---

CONTRIBUTING.rst

This resolves #251 (in case it is actually an issue).

Add quotation marks to the pip commands in CONTRIBUTING.rst

---

README.rst
docs/commands.rst
docs/index.rst

Create getting started instructions

---

setup.py

Use range for toml dependency

---

semantic_release/hvcs.py

Stumbled upon this docstring which first line seems copy/pasted from the method above.

Fix method docstring

---

docs/commands.rst
docs/configuration.rst
semantic_release/changelog/__init__.py
semantic_release/changelog/changelog.py
semantic_release/cli.py
semantic_release/defaults.cfg
semantic_release/history/logs.py
semantic_release/vcs_helpers.py
tests/test_changelog.py
tests/test_cli.py
tests/test_vcs_helpers.py

feat: Generate `changelog.md` file

---

docs/configuration.rst
semantic_release/history/logs.py
tests/history/test_changelog.py

feat: add changelog_capitalize configuration

---

semantic_release/settings.py

fix: add "changelog_capitalize" to flags

---

semantic_release/settings.py

trivial: A few settings were not in alphabetical order.

style(settings): alphabetize boolean settings

---

semantic_release/helpers.py
semantic_release/hvcs.py

This is an enhancement to fix issues related to networks errors that can occurs when using github API.
See #313

Better requests

---

semantic_release/settings.py
tests/test_settings.py

fix: crash when TOML has no PSR section

---

docs/automatic-releases/index.rst
docs/envvars.rst

docs: adding documentation for releasing on a Jenkins instance

---

semantic_release/cli.py

fix: print right info if token is not set (#360)

---

semantic_release/changelog/changelog.py
tests/test_changelog.py

fix: correct rendering of gitlab issue references

---

README.rst
semantic_release/pypi.py

Fixes ImportError raised on use of the CLI inside `semantic_release/pypi.py`.
Fixes, Resolves, and Closes Issue #376 
fixes#376
Issue Raised By: Ron Nathaniel <ronnathaniel>
PR Submitted By: Ron Nathaniel <ronnathaniel>

fix: Fixed ImproperConfig import error

---

semantic_release/hvcs.py
semantic_release/vcs_helpers.py
tests/test_hvcs.py
tests/test_vcs_helpers.py

Prefer Github/Gitlab environment variables to get owner/project

---

docs/configuration.rst
semantic_release/hvcs.py
tests/test_hvcs.py

feat: support github enterprise server

---

semantic_release/cli.py

Replicate the behavior of "version" command in version calculation.

fix(publish): get version bump for current release

---

setup.py

chore(dependencies): pin tomlkit major version only

---

docs/index.rst

docs: fix code blocks

---

.github/workflows/main.yml
.github/workflows/pr.yml
.github/workflows/stale.yml

Update actions to remove some warnings about deprecated features.

ci: Update deprecated actions

---

action.sh
action.yml

Updating the action to use configured git environment variables according to [vanilla semantic release](https://semantic-release.gitbook.io/semantic-release/usage/configuration) and [official git documentation](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables#_committing).

feat: Update action with configuration options

---

action.sh
action.yml
docs/configuration.rst

My previous contribution had some incorrect variable names that I didn't catch on first glance because english even as a native speaker is a silly silly language.

fix(action): fix environment variable names

---

semantic_release/changelog/__init__.py
semantic_release/changelog/compare.py
semantic_release/history/logs.py
semantic_release/hvcs.py
semantic_release/vcs_helpers.py

The publish process is held up by errors in the mypy step so I've fixed the errors to the best of my ability.

fix: fix mypy errors for publish

---

docs/automatic-releases/travis.rst

- spelling
- subject-verb agreement
- remove verbiage

docs: spelling and grammar in `travis.rst`

---

semantic_release/history/__init__.py
semantic_release/settings.py
semantic_release/vcs_helpers.py
tests/test_cli.py

fix: open all files with explicit utf-8 encoding

---

docs/automatic-releases/github-actions.rst

```diff
- provudes
+ provides
```

docs: fix typo

---

docs/algorithm.rst
docs/multibranch_releases.rst
semantic_release/__init__.py
semantic_release/errors.py
semantic_release/version/algorithm.py
semantic_release/version/version.py
tests/unit/semantic_release/version/test_algorithm.py
tests/unit/semantic_release/version/test_version.py

fix: skip unparseable versions when calculating next version

---

README.rst
semantic_release/cli/config.py
semantic_release/hvcs/github.py
tests/unit/semantic_release/hvcs/test_github.py

Fix issue #658 
The tests are perfectible.

fix: use correct upload url for github

---

.pre-commit-config.yaml
CHANGELOG.md
pyproject.toml
semantic_release/cli/commands/generate_config.py
semantic_release/cli/commands/main.py
semantic_release/cli/config.py
semantic_release/cli/util.py
semantic_release/version/declaration.py
tests/command_line/test_generate_config.py
tests/command_line/test_version.py
tests/unit/semantic_release/cli/test_config.py

feat: upgrade pydantic to v2

---

semantic_release/cli/masking_filter.py
tests/unit/semantic_release/cli/test_masking_filter.py

fix: attribute error when logging non-strings

---

docs/commands.rst
semantic_release/changelog/template.py
semantic_release/cli/commands/version.py
tests/command_line/test_version.py
tests/scenario/test_template_render.py

feat: allow template directories to contain a '.' at the top-level

---

.github/workflows/main.yml
.github/workflows/pr.yml
.pre-commit-config.yaml
pyproject.toml

fix!: drop support for Python 3.7

---

.github/workflows/stale.yml

- Add some additional bot help to remove the `awaiting-reply` label when an update has been received.
- Improve bot message to be more relevant contributor PRs

ci: stalebot adjustment

---

semantic_release/cli/commands/version.py
tests/command_line/test_version.py

I have seen that with Powershell fails the build command in powershell, with this fix would fix it.
Also I add pwsh which is PowerShell Core (We have Windows Powershell that detects the shell as powershell, and PowerShell Core that detects the shell as pwsh)

fix: fix build command in powershell

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md

- Help ensure all the relevant information is provided from a user with a bug report to include git repository details.
- Clean up the default templates to provide hidden instructions that are not automatically rendered in the final report. 
- Improve formatting of bug reports to make them easier to read/reference
- Add a PR template to ensure PRs are explained thoroughly and tested thoroughly

chore: improve GitHub templates

---

README.rst
action.yml
docs/index.rst

- Clarifies the purpose and scope of the github action
- Includes adjustment of README to prepare for marketplace listing

chore(gha): update action details for marketplace publishing

---

.github/workflows/main.yml

ci(main-wkflow): add file type filter to regulate testing jobs

---

action.yml
docs/automatic-releases/github-actions.rst
semantic_release/cli/github_actions_output.py
tests/unit/semantic_release/cli/test_github_actions_output.py

feat(github-actions): add `is_prerelease` output to the version action

---

docs/changelog_templates.rst
docs/configuration.rst
semantic_release/changelog/context.py
semantic_release/cli/config.py
semantic_release/data/templates/angular/md/.changelog_update.md.j2
semantic_release/data/templates/angular/rst/.changelog_header.rst.j2
semantic_release/data/templates/angular/rst/.changelog_init.rst.j2
semantic_release/data/templates/angular/rst/.changelog_update.rst.j2
semantic_release/data/templates/angular/rst/.changes.rst.j2
semantic_release/data/templates/angular/rst/.macros.rst.j2
semantic_release/data/templates/angular/rst/.unreleased_changes.rst.j2
semantic_release/data/templates/angular/rst/.versioned_changes.rst.j2
semantic_release/data/templates/angular/rst/CHANGELOG.rst.j2
tests/command_line/test_changelog.py
tests/command_line/test_version.py
tests/const.py
tests/fixtures/example_project.py
tests/fixtures/git_repo.py
tests/fixtures/repos/git_flow/repo_w_2_release_channels.py
tests/fixtures/repos/git_flow/repo_w_3_release_channels.py
tests/fixtures/repos/github_flow/repo_w_release_channels.py
tests/fixtures/repos/trunk_based_dev/repo_w_no_tags.py
tests/fixtures/repos/trunk_based_dev/repo_w_prereleases.py
tests/fixtures/repos/trunk_based_dev/repo_w_tags.py
tests/scenario/test_release_history.py
tests/unit/semantic_release/cli/test_config.py

feat(changelog): add default changelog template in reStructuredText format

---

semantic_release/changelog/template.py

fix(changelog): prevent custom template errors when components are in hidden folders

---

semantic_release/changelog/context.py
tests/unit/semantic_release/changelog/test_changelog_context.py

refactor(changelog): improve read file filter

---

semantic_release/commit_parser/angular.py
tests/fixtures/repos/git_flow/repo_w_2_release_channels.py
tests/fixtures/repos/git_flow/repo_w_3_release_channels.py
tests/fixtures/repos/github_flow/repo_w_release_channels.py
tests/fixtures/repos/trunk_based_dev/repo_w_no_tags.py
tests/fixtures/repos/trunk_based_dev/repo_w_prereleases.py
tests/fixtures/repos/trunk_based_dev/repo_w_tags.py
tests/unit/semantic_release/changelog/test_changelog_context.py
tests/unit/semantic_release/commit_parser/test_angular.py

- Improve readability of angular headings
Updated the repo fixtures and other changelog expected results

fix(parser-angular): change `Fixes` commit type heading to `Bug Fixes`

---

docs/changelog_templates.rst
semantic_release/changelog/context.py
semantic_release/cli/changelog_writer.py
tests/unit/semantic_release/changelog/test_changelog_context.py

feat(changelog): add `autofit_text_width` filter to template environment 

---

semantic_release/cli/commands/version.py

fix(cmd-version): fix `--as-prerelease` when no commit change from last full release

---

.github/workflows/ci.yml

ci(pr-wkflow): fix typo for target branch from `main` to `master`

---

src/semantic_release/cli/commands/version.py
tests/e2e/cmd_version/test_version_print.py
tests/fixtures/git_repo.py
tests/fixtures/repos/trunk_based_dev/repo_w_tags.py

fix(cmd-version): fix `--print-tag` result to match configured tag format

---

src/semantic_release/changelog/release_history.py

refactor(release-history): use proper type casting for commit msg value exclusion matching

---

src/semantic_release/commit_parser/token.py

refactor(parser): ensure commit messages are converted to strings properly

---

src/semantic_release/changelog/release_history.py
src/semantic_release/helpers.py
src/semantic_release/version/algorithm.py

fix: refactor parsing compatibility function to support older custom parsers 

---

pyproject.toml
src/semantic_release/changelog/release_history.py
src/semantic_release/commit_parser/angular.py
src/semantic_release/commit_parser/emoji.py
src/semantic_release/commit_parser/token.py
src/semantic_release/data/templates/angular/md/.components/changes.md.j2
src/semantic_release/data/templates/angular/rst/.components/changes.rst.j2
tests/e2e/cmd_changelog/test_changelog_parsing.py
tests/unit/semantic_release/commit_parser/test_angular.py
tests/unit/semantic_release/commit_parser/test_emoji.py
tests/unit/semantic_release/commit_parser/test_scipy.py

feat(parsers): add option `ignore_merge_commits` to discard parsing merge commits

---

config/release-templates/.release_notes.md.j2

chore(release-notes): update template to order issue references numerically

---

src/semantic_release/cli/config.py

- Resolves: #1169
- Resolves: #1074
Due to the previous default token loading, PSR configuration load would initate the default RemoteConfig. During validation of the remote config, the HVCS object was initialized and upon initialization the URL is evaluated for insecure protocol causing errors when the URL was pulled from the env.
This change removes the need for initialization which means the URL validation will not occur pre-maturely
Allowed user to test in their environment and it worked for them. No automated test was created.

fix(config): refactors default token resolution to prevent insecure URL error

---

pyproject.toml

chore(config): set release branch to generate dev variants

---

.github/PULL_REQUEST_TEMPLATE.md

chore(pr): add completion checklist to PR template

---

pyproject.toml

chore(config): change psr parser over to conventional-commits

---

tests/e2e/cmd_version/bump_version/git_flow/test_repo_1_channel.py
tests/e2e/cmd_version/bump_version/git_flow/test_repo_2_channels.py
tests/e2e/cmd_version/bump_version/git_flow/test_repo_3_channels.py
tests/e2e/cmd_version/bump_version/git_flow/test_repo_4_channels.py
tests/e2e/cmd_version/bump_version/github_flow/test_repo_1_channel.py
tests/e2e/cmd_version/bump_version/github_flow/test_repo_2_channels.py
tests/e2e/cmd_version/bump_version/trunk_based_dev/test_repo_trunk_dual_version_support.py
tests/e2e/cmd_version/bump_version/trunk_based_dev/test_repo_trunk_dual_version_support_w_prereleases.py
tests/e2e/cmd_version/bump_version/trunk_based_dev/test_repo_trunk_w_prereleases.py
tests/e2e/cmd_version/test_version_bump.py
tests/e2e/cmd_version/test_version_release_notes.py
tests/e2e/test_main.py

ci(tests-e2e): mark long running tests to prevent windows execution

---

pyproject.toml
src/semantic_release/__init__.py

- Eliminate the need to stamp source code with version string
---

refactor: pull project version variable from package metadata

---

CHANGELOG.rst
docs/api/commands.rst
docs/configuration/automatic-releases/travis.rst

chore(changelog): update changelog spelling, links, & shorten breaking change descriptions

---

src/semantic_release/data/templates/conventional/md/.components/macros.md.j2
src/semantic_release/data/templates/conventional/rst/.components/macros.rst.j2

refactor(changelog): simplify & consolidate jinja macro functionality

---

src/semantic_release/cli/changelog_writer.py
src/semantic_release/cli/config.py
src/semantic_release/commit_parser/_base.py
src/semantic_release/commit_parser/angular.py
src/semantic_release/commit_parser/scipy.py
src/semantic_release/commit_parser/token.py
src/semantic_release/commit_parser/util.py
tests/unit/semantic_release/commit_parser/test_conventional.py
tests/unit/semantic_release/commit_parser/test_emoji.py
tests/unit/semantic_release/commit_parser/test_scipy.py

chore: update in code todos for v10

---

docs/api/commands.rst
docs/configuration/configuration-guides/index.rst
docs/configuration/configuration-guides/uv_integration.rst
docs/configuration/index.rst
src/semantic_release/cli/commands/version.py
tests/e2e/cmd_version/test_version_stamp.py

Fixes https://github.com/python-semantic-release/python-semantic-release/issues/1211
This was @codejedi365's suggestion in #1211
See the PR; @codejedi365 wrote automated tests
See the PR; @codejedi365 wrote documentation
---

fix(version): always stage updated files

---

src/semantic_release/cli/util.py

fix(util): fixes no-op log output when commit message contains square-brackets

---

action.yml
docs/configuration/automatic-releases/github-actions.rst
src/semantic_release/cli/commands/version.py
src/semantic_release/cli/github_actions_output.py
tests/e2e/cmd_version/test_version_github_actions.py
tests/unit/semantic_release/cli/test_github_actions_output.py

feat(github-actions): add `commit_sha` as a GitHub Actions output value

---

action.yml
docs/configuration/automatic-releases/github-actions.rst
src/semantic_release/cli/commands/version.py
src/semantic_release/cli/github_actions_output.py
tests/e2e/cmd_version/test_version_github_actions.py
tests/unit/semantic_release/cli/test_github_actions_output.py

feat: add release link to github action outputs
